### ISSUE TITLE
Creating Execute task with multiple commands in a line

### ISSUE THREAD

**Issue by fr0z3nfyr** [dereuromark/cakephp-queue#105]
Hi, thanks for the super useful plugin which I think is much better than Resque for performing basic background/queued tasks.

This post is more of a query than an issue report: 
My implementation of this plugin went pretty well so far and have no complaints.
I want to queue a job from my controller which will first change directory then execute a script in that directory like `cd /path/to/scripts/directory && php myscript.php some_argument`. Right now, my code in controller is 
```
$queue_data = array(
	'command' => 'php',
	'params' => array(
		'/path/to/scripts/directory/myscript.php',
		'some_argument',
	)
);

$this->QueuedTask->createJob('Execute', $queue_data);
```
which executes the command `php /path/to/scripts/directory/myscript.php some_argument`

Is there a way that I can modify this controller code to include multiple commands to be run together like I said above. This is just an example, I'm planning to execute few other linked scripts that have relative paths inside them. So, if I try to call those scripts from any other directory, they will error out. I do not want to use absolute paths in the files because it will be a pain when I move my files from development to production server with different paths.

**Comment by dereuromark** [comment]
You can also just execute multiple createJob() with each its own command and params.
Probably easier.

**Comment by fr0z3nfyr** [comment]
Thanks for the suggestion but it won't work in all cases. What about the cases when I want to pipe output of first to next statement?

What will happen if the 2nd command is dependent on the output of first? Consider a case: `worker 1` allocates few queue items including said 1st task to be last in it's queue. `worker 2` takes said 2nd task to be first in it's queue. `worker 2` executes 2nd task before `worker 1` could finish (for that matter, even start, because of few email jobs ahead in queue) 1st task. That will be a disaster.

I can anticipate that you might suggest calling that second command from within the first task's script... I can do that and that's how I'm doing it right now but still looking for a better solution than this!

Thanks in advance!
