### ISSUE TITLE
Note on Setting up the trigger cronjob in README

### ISSUE THREAD

**Issue by fr0z3nfyr** [dereuromark/cakephp-queue#107]
I had few problems when I added the queue worker to my `crontab` because of my stupidity, of course. I had created the cron job using `crontab -e` while I was superuser. That created few cache files that were owned by `root` and then I started having app performance issues due to problems with cache. 

All I had to do was remove the cron job from my root crontab and put it into `www-data` crontab by using `crontab -u www-data -e`. I noticed that you did comment this on one of the closed issues [here](https://github.com/dereuromark/cakephp-queue/issues/61#issuecomment-141001016). But I feel it will be a favor to write it down in README for many hasty people (like myself :disappointed_relieved: ) 

Thanks again for the plugin!

**Comment by dereuromark** [comment]
Can you please make PR for https://github.com/dereuromark/cakephp-queue/tree/master/docs#setting-up-the-trigger-cronjob ? That would be awesome.

**Comment by dereuromark** [comment]
I added it.
