### ISSUE TITLE
Queue Task not mark as completed

### ISSUE THREAD

**Issue by nutii** [dereuromark/cakephp-queue#110]
Hi, I have problem with marking task as completed. 

After command:
bin/cake Queue.Queue runworker
I have next message

Running Job of type MyType

MyTaskNameQueue task run.

Success     

Job Finished.    

But field "completed" set to NULL . Using your last version. CakePHP 3.2.14. 
After some analysis, I found that the Entity does not change after patchEntity().
(here: /vendor/dereuromark/cakephp-queue/src/Model/Table/QueuedTasksTable.php):
`
public function markJobDone(QueuedTask $task) {
		$fields = [
			'completed' => date('Y-m-d H:i:s'),
		];
		$task = $this->patchEntity($task, $fields);
		return (bool)$this->save($task);
	}
`
Please tell me what I'm doing wrong ?

**Comment by dereuromark** [comment]
whats the last version? the tag? dev master or dev develop?

**Comment by nutii** [comment]
"version": "dev-master"

**Comment by dereuromark** [comment]
Bear in mind that this is not marked as stable - it changes the serialize to json encode.
Maybe that is your issue?

**Comment by nutii** [comment]
Thanks, I found that version 3.3.2 work fine. Maybe you have a point here. I will analyse it, thanks a lot!
