### ISSUE TITLE
completed datetime wrong

### ISSUE THREAD

**Issue by awallef** [dereuromark/cakephp-queue#112]
Hi found a little issue at line 272...

following worked for me.
src/Model/Table/QueuedJobsTable.php line 271

`$fields = [
 'completed' => new Time(),
];`

Thanks

**Comment by dereuromark** [comment]
Are you able to make a PR here? That would be awesome.

**Comment by dereuromark** [comment]
Thanks for https://github.com/dereuromark/cakephp-queue/pull/113

**Comment by awallef** [comment]
welcome, thanks for your work, very helpful!
