### ISSUE TITLE
Invalid log level "email_error"

### ISSUE THREAD

**Issue by busgurlu** [dereuromark/cakephp-queue#115]
An exception is thrown from cakephp/cakephp/src/Log/Log.php, line 366 when there is an SMTP error and it is tried to be logged as "email_error" in https://github.com/dereuromark/cakephp-queue/blob/e742d54872a4f2aaee39fe699da9379c74c172c1/src/Shell/Task/QueueEmailTask.php#L98

**Comment by dereuromark** [comment]
You are right, the 2.x way here doesn't work anymore.
Any ideas on the fix for logging into a custom file?

**Comment by dereuromark** [comment]
We need to fix up https://github.com/dereuromark/cakephp-queue/blob/master/src/Shell/Task/QueueEmailTask.php#L143-L149

**Comment by dereuromark** [comment]
Fixed in master. Please confirm.
