### ISSUE TITLE
Job not found

### ISSUE THREAD

**Issue by ehuebner** [dereuromark/cakephp-queue#116]
Hi,
i installed everything like in the Doc. Plugin Working, jobs can be created. 
I want to run a job in my custom task with the name "Notification".
I have the following job in the database: (i removed the data)
```
`id`, `job_type`, `data`, `job_group`, `reference`, `created`, `notbefore`, `fetched`, `completed`, `progress`, `failed`, `failure_message`, `workerkey`, `status`, `priority`

19, 'Notification', '', NULL, NULL, '2017-02-28 19:39:34', NULL, '2017-02-28 19:43:31', '2017-02-28 19:43:31', NULL, 0, NULL, 'd8a4fd0c83758f61e3ad5253e4ea772472083920', NULL, 5
```
(Sorry i wanted to upload a picture but it fails at Gitlab. 37kb image upload not working.

The job was added with the command:
```TableRegistry::get('Queue.QueuedJobs')->createJob('Notification', $notification);```

The following file is placed in the src/Shell/Task folder:
```
<?php
namespace App\Shell\Task;
use Queue\Shell\Task\QueueTask;
class QueueNotificationTask extends QueueTask
{
	public function run(array $data, $id) {

		//$this->processNotificationJob($data);

		return true;
	}
```
The task is recognized and when i exec 
`./bin/cake.php queue status`
i get:
```
Available Tasks:
* Notification
* Email
* Example
* Execute
* LongExample
* RetryExample
* SuperExample
```

But when i run
`./bin/cake.php queue runworker`
while i am in the app home the job will not be found. I just get:
`[2017-02-28 19:55:44] Looking for Job ... nothing to do, sleeping.`

So basicly the task will be found but not the job that is in the database.

I use PHP 5.5.19 and CakePHP v3.3.11.

Any ideas?

Thanks a lot!

**Comment by tuffz** [comment]
I have the same problem with PHP 5.5.36 and CakePHP v3.3.15

**Comment by dereuromark** [comment]
Can you debug it, why it doesnt find it? What is the generated SQL query etc?

**Comment by ehuebner** [comment]
At some point it started working but i was not able recognize it.
Closed.
