### ISSUE TITLE
documentation is unclear and difficult for newbies

### ISSUE THREAD

**Issue by anujsharma9196** [dereuromark/cakephp-queue#119]
I'm new to cron, shell and tasks. 

In my project, I have to run some task in background on user's action which might take a long time in its completion.

As far as I have understand your documentation.

I have created a task in` /app/src/Shell/Task `named `QueueScanTask.php` with following contents

```
<?php
namespace App\Shell\Task;

use Cake\Console\Shell;
use Queue\Shell\Task\QueueTask;

/**
 * QueueScan shell task.
 */
require ROOT . DS . 'vendor/scanners/Scanner.php';

class QueueScanTask extends QueueTask
{
    public function initialize()
    {
        parent::initialize();
        $this->loadModel('Users');
        $this->loadModel('UserServers');
    }

    public function add()
    {
        $this->out('Task is adding by me');
        $this->out('');
            $this->loadModel('TestingCron');
            $a = [
                'data' => 'abc'
            ];
            $t_c = $this->TestingCron->newEntity($a);
            $this->TestingCron->save($t_c);
    }

    public function run(array $data, $id)
    {
        $this->loadModel('TestingCron');
        $a = [
             'data' => $data['dir'],
        ];
        $t_c = $this->TestingCron->newEntity($a);
        $this->TestingCron->save($t_c);
    }
}
```

Data here is for testing... what I have to do is to pass some parameters to the task in order to further execute the task.

In my controller, I'm creating job using
    
```
public function test()
{
     $this->loadModel('Queue.QueuedJobs');
     $this->QueuedJobs->createJob('Scan', ['id' => 5, 'dir' => 'my_folder']);
}
```

But this is only creating a new entry to `QueuedJobs` but not creating entry in TestingCron table.

I couldn't understand the flow of the new queued job.

Is there something wrong I'm doing?

**Comment by dereuromark** [comment]
/app/src/Shell/Tasks => /app/src/Shell/Task

And the cron table is not in use.
Did you run the worker? Only that will take the queued jobs and then process them.

**Comment by anujsharma9196** [comment]
Do I need to run worker manually?

If yes, how can I start worker from controller after creating a job ?
Also, Can I recreate same job when worker is processing job created ?

**Comment by dereuromark** [comment]
Yes.
You dont, those are creating from CLI (crontab tool etc) as documented.

Please read more about how it works. This is not a helpdesk but a bugtracker. There are forums and other ways of community help programs. Closing now.
