### ISSUE TITLE
Duplicates with concurrent workers

### ISSUE THREAD

**Issue by tyalcinkaya** [dereuromark/cakephp-queue#121]
We have a task that runs once a day and creates x number of tasks/jobs for that day.  When the load on smallest linode instance became too high, we decided to launch another server instance to run an additional queue worker.

With a _single worker_ running on a _single machine_, **all was fine**. But... when we launched the second server instance, we noticed that **duplicate tasks** being created.   Further investigation is showing that with multiple workers some tasks are run twice!

We reverted back to using a single worker, but would like to run multiple instances.

@dereuromark : Any idea what's going on?

**Settings**:
- workermaxruntime: 900
- sleeptime: 11
- pidfilepath: /tmp/queue/
- cleanuptimeout: 604800
- gcprob: 10
- defaultworkertimeout: 1800
- defaultworkerretries: 3
- exitwhennothingtodo: false
- log: true
- notify: tmp 

**Running**:
- Ubuntu 16.04
- PHP Version => 5.6.30-5+deb.sury.org~xenial+2
- MySQL 5.7.18-0ubuntu0.16.04.1    ENGINE=InnoDB

```

	"name": "dereuromark/cakephp-queue",
	"version": "dev-master",
	"source": {
	    "type": "git",
	    "url": "https://github.com/dereuromark/cakephp-queue.git",
	    "reference": "20d0e21a9b13b081ae8fcc12f9dbb9b2b838a3f3"
	},

```

**Comment by dereuromark** [comment]
You could investigate why it creates those duplicates? Maybe some lock mechanism doesnt work properly anymore.
I really only use the single worker on a very basic app, or at least one worker per type approach.
I would also recommend to switch to a more sophisticated system if you need more.

**Comment by tyalcinkaya** [comment]
It seems like the culprit is  `$this->connection()->transactional(...)` line in `QueuedJobsTable::requestJob(..)`  It is not locking the row/record for reads and updates. 

This line should have [exclusive lock](https://dev.mysql.com/doc/refman/5.7/en/innodb-locking-reads.html) on the row.  More specifically (for MySQL) it needs to use `SELECT … FOR UPDATE` so that all other workers won't be able to read or update the row.  Once the transaction committed or rolled-back, other workers will be able to read this row again.

I feel that cakephp-queue is robust enough for most scenarios.  It already supports multiple workers.  So, exclusive read lock is needed to make sure that duplicates won't create problems for other users.

As for switching to something else, well.... I would rather try to help you make cakephp-queue better first :-)  Switching to something else would be painful and lengthy migration for us.

**Comment by dereuromark** [comment]
If you have a PR of some code changes in mind please PR that. I agree that we should aim to make it even more robust :)

**Comment by tyalcinkaya** [comment]
Sure... It may take a couple of weeks for me to get to it, but I will fix this and send you a pull request.

**Comment by mattvision** [comment]
Thanks tyalcinkaya, this worked for me:
$job = $query->find('all', $options)->autoFields(true)->epilog('FOR UPDATE')->first();
Cheers.

**Comment by dereuromark** [comment]
Please make a PR Guys :) thanks a Lot.

**Comment by dereuromark** [comment]
Any updates regarding this issue?
I couldnt reproduce so far

Also: The 3.5 version now uses no files anymore, so it should also be better now.
It also logs the processes run better:

    job Demo, id 10 (pid 182) 
    job Example, id 9 (pid 2850) 

That can help track down the issue maybe.

**Comment by dereuromark** [comment]
It is also important to set the timeout high enough for each task:
https://github.com/dereuromark/cakephp-queue/blob/master/src/Shell/Task/QueueTask.php#L35

if the $timeout is too short, it will pick it up even though it is still running...
