### ISSUE TITLE
Full base URL in e-mail sent by CLI

### ISSUE THREAD

**Issue by lorro** [dereuromark/cakephp-queue#123]
Hi Mark,

I'm having some issues formatting correct full links in the e-mail template which I use for an e-mail sent by the CLI.
I have created myself a custom shell task that sends an e-mail in the following manner
````php
$email
->to($to)
->subject($data['subject'])
->template('products' . DS . 'stockmail')
->setDomain('rlvpr.be')
->domain('rlvpr.be')
->send();
````

The e-mails get sent but I get urls as this one: http://localhost/nl/product-groups/view/slug instead of the correct domain name in it. 
Built it like 
`echo $this->Url->build(['controller' => 'ProductGroups', 'action' => 'view', $product->slug, 'prefix' => false], true);`
Did try both "domain" as "setDomain" function on the e-mail object but none of them does the trick. Doesn't seem to pick up the correct host name. Also images don't show anymore because of this.

Any idea what could be the problem? It seems I'm doing the same thing as in the docs example?

Thanks!

**Comment by dereuromark** [comment]
You might have forgotten App.fullBaseUrl
See https://book.cakephp.org/3.0/en/console-and-shells.html#routing-in-shells-cli

**Comment by lorro** [comment]
In bootstrap_cli.php I've actually got this set up 
````php
// Set the fullBaseUrl to allow URLs to be generated in shell tasks.
// This is useful when sending email from shells.
Configure::write('App.fullBaseUrl', 'https://rlvpr.be');
````

**Comment by lorro** [comment]
Apparently that got overwritten by what cakePHP did in the bootstrap.php file ...
````
/*
 * Set the full base URL.
 * This URL is used as the base of all absolute links.
 *
 * If you define fullBaseUrl in your config file you can remove this.
 */
if (!Configure::read('App.fullBaseUrl')) {
    $s = null;
    if (env('HTTPS')) {
        $s = 's';
    }

    $httpHost = env('HTTP_HOST');
    if (isset($httpHost)) {
        Configure::write('App.fullBaseUrl', 'http' . $s . '://' . $httpHost);
    }
    unset($httpHost, $s);
}
````

So I commented these lines out and put the fullBaseUrl manually in the bootstrap.php also.

Thanks
