### ISSUE TITLE
Trigger failure with message from run()

### ISSUE THREAD

**Issue by anuj9196** [dereuromark/cakephp-queue#126]
Can I trigger a failure message with failed set to true and custom message directly from `run()` method of my task

```
$postVideo = $this->PostVideos->get($data['post_video_id']);
if ($postVideo) {
    if (empty($postVideo->campaign_id)) {
        $this->log('No associated campaign found', 'error');

        // set failed to true in queued_jobs table with no re-queue or retry
     }
     // else go ahead
     ...
     ...
}
```

**Comment by dereuromark** [comment]
Can you please make a PR if there is sth to fix here?

**Comment by dereuromark** [comment]
What value have to set for retries of your task?
https://github.com/dereuromark/cakephp-queue/blob/master/src/Shell/Task/QueueTask.php#L42

Make sure this is very low if you do not want it to re-run after failing.

**Comment by dereuromark** [comment]
I improved both documentation and the feedback here.
In fact it always said "requeued" even if aborted, this is now also resolved :) It was only a cosmetic thing, the functionality was always behaving correctly!
