### ISSUE TITLE
can you remove .git from installation

### ISSUE THREAD

**Issue by anuj9196** [dereuromark/cakephp-queue#128]
Recently, I installed this plugin in my application which I have to push to my gitlab account using git

Since this plugin contains `.git` directory in the root, the plugin was not pushed and now it is being treated as a submodule.

Can you remove `.git` directory from installation because I don't think it is of any use for user who is using this plugin.

**Comment by Spriz** [comment]
The .git folder is something Git is creating - it's not in the VCS (take a look here: https://github.com/dereuromark/cakephp-queue)

**Comment by dereuromark** [comment]
I tagged a new patch release https://github.com/dereuromark/cakephp-queue/releases/tag/3.4.1
So please always use tags if possible: `composer require ...` does that for you automatically.
Try to avoid dev-master and you won't have any git repo.
