### ISSUE TITLE
console queue add not working

### ISSUE THREAD

**Issue by ehuebner** [dereuromark/cakephp-queue#129]
When i run 
`./bin/cake queue add MyExistingQueue`
i does not create a queue jon in the database. The `-v` does not have any effect.
Any ideas how i can figure out what is the issue?

Thanks a lot.

**Comment by anuj9196** [comment]
The task name must be 
```
QueueMyExistingTask
``` 
and there should be an `add()` function within it which adds queue to `queued_jobs` table 
```
$this->QueuedJobs->createJob('MyExisting', ['id' => $id])
```
`['id' => $id]` is optional data

and then run from shell
```
bin/cake queue add MyExisting
```

**Comment by ehuebner** [comment]
Hi,
thanks for your reply.
Adding in code is working perfectly for me. I have implemented >5 Jobs and everything is running as intended.

From shell i did it exactly the way you just mentioned and it does not work. To be clear i use the name like it is in the list of available task when i type the following in the shell.
`./bin/cake queue add`

"MyExistingQueue" was the name like it is shown in that list.

The output is get is only the cake console output but the output from the queue add command is empty. Is this as intended?

**Comment by anuj9196** [comment]
Share your code what you are having in `add()`

**Comment by ehuebner** [comment]
Oh, my fault. Documentation is not very clear at that point.
