### ISSUE TITLE
STMP fails with 550 Requested action not taken! No access.

### ISSUE THREAD

**Issue by mubasshir** [dereuromark/cakephp-queue#134]
When I'm seding email via CakePHP SMTP it works fine but When I'm calling same function in runworker, I'm getting this error

> 550 Requested action not taken! No access.

**Comment by mubasshir** [comment]
Why did you close it? Any resolution?

**Comment by dereuromark** [comment]
This is not a queue issue. The smtp is probably not used here, but mail or sth.
You need to fix the way you submit your data here.
