### ISSUE TITLE
Configure value Queue.notify is not being used anywhere

### ISSUE THREAD

**Issue by inoas** [dereuromark/cakephp-queue#139]
In `app_queue.php`

```php
		// set to false to disable (tmp = file in TMP dir)
		'notify' => 'tmp',
```

At least a quick find through all files for `notify` did not reveal that it is being used anywhere.
Also it is unclear to me what "notification" has to do with the TMP dir?!

**Comment by dereuromark** [comment]
i guess some 2.x relict. can be removed
