### ISSUE TITLE
Use LONGTEXT for failure_message

### ISSUE THREAD

**Issue by inoas** [dereuromark/cakephp-queue#146]
I am storing quite big error messages inside possibly a few hundred KB of utf8 CSS.
Would it hurt to change the column type from TEXT to ~~LONGTEXT~~ MEDIUMTEXT?

Edit: Or MEDIUMTEXT for that matter.
https://mariadb.com/kb/en/library/text/
https://mariadb.com/kb/en/library/mediumtext/
https://mariadb.com/kb/en/library/longtext/

**Comment by dereuromark** [comment]
Afaik this is already done: https://github.com/dereuromark/cakephp-queue/blob/master/config/Migrations/20161319000000_increase_data_size.php

**Comment by dereuromark** [comment]
If the `if ($adapter->getSqlType('text', 'longtext')) {}` is not working, maybe we should remove it?

**Comment by inoas** [comment]
Well all I did was running the migrations without thinking about it.
Then when I wanted to change the database field I noticed that that's not the way to do it ;-)

Also I think mediumtext is sufficient, longtext can bog down a system if things go wrong.

p.s.: I am storing only id/revision_id as the data to process - but I want to have the full failure message of the unix process in the log for easy reporting. And well... that includes some print statements and say javascript sources.

**Comment by inoas** [comment]
Would this run for MariaDB? https://github.com/dereuromark/cakephp-queue/blob/master/config/Migrations/20161319000000_increase_data_size.php#L23

**Comment by inoas** [comment]
https://github.com/dereuromark/cakephp-queue/blob/c655181a66cbd2a89793971929350346c171e1a4/config/Migrations/20161319000000_increase_data_size.php#L24

```php
if ($adapter->getSqlType('text', 'longtext')) {
```
... returns "text" for me on MariaDB 10.2
What about you?

**Comment by inoas** [comment]
Probably an issue with phinx

**Comment by dereuromark** [comment]
Maybe we have to fix this check.
I am sure it is only in there because of postgres :)

**Comment by inoas** [comment]
I just figured... `data` is actually mediumtext but `failure_message` is not.
In data I just store a reference but in `failure_message` in the case of asset processing I want to store the failed asset data.
