### ISSUE TITLE
Use utf8mb4 instead of utf8

### ISSUE THREAD

**Issue by inoas** [dereuromark/cakephp-queue#147]
### Reason

Ref: https://mathiasbynens.be/notes/mysql-utf8mb4
Can this be taught to the cakephp migrations utilized by cakephp-queue?

### Case insensitive SQL Match

```regexp
^varchar\((\d+)\)(?:(?!\s+CHARACTER).)*$
```

Replace:

```regexp
varchar($1) CHARACTER SET utf8mb4 DEFAULT
```
https://regex101.com/r/3xWfUp/1
Edit same for tinytext, text, mediumtext, longtext, char

And `ENGINE=InnoDB DEFAULT CHARSET=utf8;` => `ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`

**Comment by dereuromark** [comment]
I already use it everywhere thanks to https://www.dereuromark.de/2016/11/11/emoji-and-cakephp/
If this plugin doesnt yet, please make a PR with the fixes to mgiration.
