### ISSUE TITLE
Cannot send email

### ISSUE THREAD

**Issue by exc4li3ur** [dereuromark/cakephp-queue#151]
Hope that I can get answer here
I have already install a new cakephp dan cakephp-queue on my machine. But it didn't work when queueworker send the email.

I always get this error :

2017-10-16 07:08:44 Warning: Warning (2): call_user_func_array() expects parameter 1 to be a valid callback, class 'Cake\Mailer\Email' does not have a method 'viewConfig' in [D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Queue\Shell\Task\QueueEmailTask::run() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110
Queue\Shell\QueueShell::runworker() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\QueueShell.php, line 169
Cake\Console\Shell::runCommand() - CORE\src\Console\Shell.php, line 494
Cake\Console\CommandRunner::run() - CORE\src\Console\CommandRunner.php, line 141
[main] - ROOT\bin\cake.php, line 12

2017-10-16 07:08:44 Warning: Warning (2): call_user_func_array() expects parameter 1 to be a valid callback, class 'Cake\Mailer\Email' does not have a method '_to' in [D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Queue\Shell\Task\QueueEmailTask::run() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110
Queue\Shell\QueueShell::runworker() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\QueueShell.php, line 169
Cake\Console\Shell::runCommand() - CORE\src\Console\Shell.php, line 494
Cake\Console\CommandRunner::run() - CORE\src\Console\CommandRunner.php, line 141
[main] - ROOT\bin\cake.php, line 12

2017-10-16 07:08:44 Warning: Warning (2): call_user_func_array() expects parameter 1 to be a valid callback, class 'Cake\Mailer\Email' does not have a method '_from' in [D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Queue\Shell\Task\QueueEmailTask::run() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110
Queue\Shell\QueueShell::runworker() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\QueueShell.php, line 169
Cake\Console\Shell::runCommand() - CORE\src\Console\Shell.php, line 494
Cake\Console\CommandRunner::run() - CORE\src\Console\CommandRunner.php, line 141
[main] - ROOT\bin\cake.php, line 12

2017-10-16 07:08:44 Warning: Warning (2): call_user_func_array() expects parameter 1 to be a valid callback, class 'Cake\Mailer\Email' does not have a method '_subject' in [D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Queue\Shell\Task\QueueEmailTask::run() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110
Queue\Shell\QueueShell::runworker() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\QueueShell.php, line 169
Cake\Console\Shell::runCommand() - CORE\src\Console\Shell.php, line 494
Cake\Console\CommandRunner::run() - CORE\src\Console\CommandRunner.php, line 141
[main] - ROOT\bin\cake.php, line 12

2017-10-16 07:08:44 Warning: Warning (2): call_user_func_array() expects parameter 1 to be a valid callback, class 'Cake\Mailer\Email' does not have a method '_emailFormat' in [D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Queue\Shell\Task\QueueEmailTask::run() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110
Queue\Shell\QueueShell::runworker() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\QueueShell.php, line 169
Cake\Console\Shell::runCommand() - CORE\src\Console\Shell.php, line 494
Cake\Console\CommandRunner::run() - CORE\src\Console\CommandRunner.php, line 141
[main] - ROOT\bin\cake.php, line 12

2017-10-16 07:08:44 Warning: Warning (2): call_user_func_array() expects parameter 1 to be a valid callback, class 'Cake\Mailer\Email' does not have a method '_emailPattern' in [D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Queue\Shell\Task\QueueEmailTask::run() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110
Queue\Shell\QueueShell::runworker() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\QueueShell.php, line 169
Cake\Console\Shell::runCommand() - CORE\src\Console\Shell.php, line 494
Cake\Console\CommandRunner::run() - CORE\src\Console\CommandRunner.php, line 141
[main] - ROOT\bin\cake.php, line 12

2017-10-16 07:08:44 Warning: Warning (2): call_user_func_array() expects parameter 1 to be a valid callback, class 'Cake\Mailer\Email' does not have a method '_domain' in [D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Queue\Shell\Task\QueueEmailTask::run() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110
Queue\Shell\QueueShell::runworker() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\QueueShell.php, line 169
Cake\Console\Shell::runCommand() - CORE\src\Console\Shell.php, line 494
Cake\Console\CommandRunner::run() - CORE\src\Console\CommandRunner.php, line 141
[main] - ROOT\bin\cake.php, line 12

2017-10-16 07:08:44 Warning: Warning (2): call_user_func_array() expects parameter 1 to be a valid callback, class 'Cake\Mailer\Email' does not have a method '_messageId' in [D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Queue\Shell\Task\QueueEmailTask::run() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110
Queue\Shell\QueueShell::runworker() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\QueueShell.php, line 169
Cake\Console\Shell::runCommand() - CORE\src\Console\Shell.php, line 494
Cake\Console\CommandRunner::run() - CORE\src\Console\CommandRunner.php, line 141
[main] - ROOT\bin\cake.php, line 12

2017-10-16 07:08:44 Warning: Warning (2): call_user_func_array() expects parameter 1 to be a valid callback, class 'Cake\Mailer\Email' does not have a method '_appCharset' in [D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 153
Queue\Shell\Task\QueueEmailTask::run() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php, line 110
Queue\Shell\QueueShell::runworker() - ROOT\vendor\dereuromark\cakephp-queue\src\Shell\QueueShell.php, line 169
Cake\Console\Shell::runCommand() - CORE\src\Console\Shell.php, line 494
Cake\Console\CommandRunner::run() - CORE\src\Console\CommandRunner.php, line 141
[main] - ROOT\bin\cake.php, line 12

2017-10-16 07:08:44 Error: QueueEmail
BadMethodCallException: You need specify one destination on to, cc or bcc.
#0 D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\Task\QueueEmailTask.php(126): Cake\Mailer\Email->send(NULL)
#1 D:\xampp\htdocs\e-commerce\vendor\dereuromark\cakephp-queue\src\Shell\QueueShell.php(169): Queue\Shell\Task\QueueEmailTask->run(Array, 8)
#2 D:\xampp\htdocs\e-commerce\vendor\cakephp\cakephp\src\Console\Shell.php(494): Queue\Shell\QueueShell->runworker()
#3 D:\xampp\htdocs\e-commerce\vendor\cakephp\cakephp\src\Console\CommandRunner.php(141): Cake\Console\Shell->runCommand(Array, true)
#4 D:\xampp\htdocs\e-commerce\bin\cake.php(12): Cake\Console\CommandRunner->run(Array)
#5 {main}

**Comment by dereuromark** [comment]
How did you add a job? You need to paste your code here and the data you are passing to it.

**Comment by stmeyer** [comment]
I've the same error. Configuration:
```php
    'EmailTransport' => [
        'default' => [
            'className' => 'Smtp',
            // The following keys are used in SMTP transports
            'host' => 'host',
            'port' => 25,
            'timeout' => 30,
            'username' => 'user',
            'password' => 'secret',
            'client' => null,
            'tls' => null,
        ],
        'queue' => [
            'className' => 'Queue.Queue',
            'transport' => 'default'
        ],
    ],
    'Email' => [
        'default' => [
            'transport' => 'queue',
            'from' => 'mail@example.com',
            'charset' => 'utf-8',
            'headerCharset' => 'utf-8',
        ],
    ],
```
Send an E-Mail in a controller:
```php
        $email = new \Cake\Mailer\Email('default');
        $email->from(['mail@example.com' => 'Example'])
            ->to('mail@example.com')
            ->subject('About')
            ->send('My message');
```

The $data in method `run` https://github.com/dereuromark/cakephp-queue/blob/84be4efd266a06972d011b82acd605e5e495bb07/src/Shell/Task/QueueEmailTask.php#L70 has the content:
```php
[
        'transport' => 'default',
        'settings' => [
                'viewConfig' => [
                        '_layout' => 'default',
                        '_className' => 'Cake\View\View',
                        '_helpers' => [
                                (int) 0 => 'Html'
                        ]
                ],
                '_to' => [
                        'mail@example.com' => 'mail@example.com'
                ],
                '_from' => [
                        'mail@example.com' => 'Example'
                ],
                '_subject' => 'About',
                '_emailFormat' => 'text',
                '_emailPattern' => '/^((?:[\p{L}0-9.!#$%&'*+\/=?^_`{|}~-]+)*@[\p
{L}0-9-.]+)$/ui',
                '_domain' => '******',
                '_messageId' => true,
                '_appCharset' => 'UTF-8',
                'charset' => 'utf-8',
                'headerCharset' => 'utf-8'
        ]
]
```

**Comment by dereuromark** [comment]
Do you have an idea of a fix as PR?

**Comment by stmeyer** [comment]
I think it is because of commit https://github.com/dereuromark/cakephp-queue/commit/7ab4d157afb8178189116f4adb0c631bff19a99b "Use json_encode() instead of serialize". JSON can not be converted back to an PHP object. Instead of it is always converted into an array. And the line https://github.com/dereuromark/cakephp-queue/blob/84be4efd266a06972d011b82acd605e5e495bb07/src/Shell/Task/QueueEmailTask.php#L78 checks for an object that could not be found

**Comment by dereuromark** [comment]
Maybe also security issue I think? 
But the actual main issue is any change to Email object would also not serialize it back.
So if you update your vendor (core) you would otherwise need to make sure the queue is empty.

Is there a way to jeep json_encode() and provide a mapping here for the option/config setting etc?

**Comment by stmeyer** [comment]
At the moment I do not see another way than reading out every configuration by calling all getters in `QueueTransport`  into an array and writing this array into the database. In `QueueEmailTask` every configuration has to be written into the mail by calling all getters.

I tried something with `get_class_methods` but some getters form Email-class have parameters sothat I think it has to be done manually.

Or has anyone an other idea?

**Comment by dereuromark** [comment]
We can also switch back to the serialize then for the time being. Please make a PR.
