### ISSUE TITLE
RFC: Make json_encode and serialize configurable

### ISSUE THREAD

**Issue by stmeyer** [dereuromark/cakephp-queue#155]
How do you think about making the use of json_encode and serialize configurable? I thnk of two options:

1. configure it globally for all task types `$config['Queue']['useJson'] = true;`
1. configure it in each task class, maybe with a class constant. This is more flexible

I have not check what changes in source have to be done.

**Comment by dereuromark** [comment]
I would rather recommend adding a specific QueueEmailTask for it, e.g. QueueSerializedEmailTask (current one) and QueueEmailTask (json then). So people can decide without having to use config option overhead and hidden switches and complexity.

**Comment by dereuromark** [comment]
We should clean this all up a bit.
See https://github.com/dereuromark/cakephp-queue/tree/master/docs#difference-between-queuetransport-and-simplequeuetransport

**Comment by dereuromark** [comment]
Ah now I know what the problem is: We changed serialize() for all jobs, not just for email related ones...
In that case it would really make sense to adjust this to keep JSON by default for all expect a few custom ones that require serialize()..

**Comment by inoas** [comment]
What about a Core\Json class that can be configured through Configure:: to set (default, and runtime) params for json_encode/json_decode and throws exceptions instead of those json last errors?

**Comment by dereuromark** [comment]
I would like to make a new release, but for that we should probably start finalizing this serialize topic.
To have a more stable API now.

**Comment by stmeyer** [comment]
I'm sorry but I have new priorities and I'm not able to help you in the near future

**Comment by dereuromark** [comment]
@stmeyer @inoas Implemented in https://github.com/dereuromark/cakephp-queue/pull/353
