### ISSUE TITLE
Disable auto cleanup

### ISSUE THREAD

**Issue by anuj9196** [dereuromark/cakephp-queue#157]
I want to disable cleanup completely as I'm handling this manually in my application as per my requirement.

How to disable `cleanuptimeout`?
```
$config['Queue']['cleanuptimeout'] = 2592000; // 30 days
```

**Comment by dereuromark** [comment]
does 0 work?

**Comment by dereuromark** [comment]
Added with https://github.com/dereuromark/cakephp-queue/commit/cce051d28fbd4720f1e06fba9f85f2e9fd8a5e46
