### ISSUE TITLE
components in task

### ISSUE THREAD

**Issue by ckrempe** [dereuromark/cakephp-queue#161]
Is it possible to use cakePHP 3.5.  components in cakephp-queue?
For example my component MyApiComponent.php

`use Cake\Controller\Component;
...
$response = $this->MyApi->get($url);`

doesn't work for me.

Thanks

Christoph

**Comment by dereuromark** [comment]
This shoudnt be a component then, but a task - or refactor into a business class (Lib) and incklude that one.
Components are "helpers of controllers" only, never ever for sth else.
