### ISSUE TITLE
job status reporting

### ISSUE THREAD

**Issue by ckrempe** [dereuromark/cakephp-queue#163]
Creating a job in my JobController.php works:

`$this->loadModel('Queue.QueuedJobs');
  $myjob = $this->QueuedJobs->createJob(ucfirst($params['jobtype']), $params);
 $id = $myjob->id;`

Now I want to report the job progress as described in Docu -> 'Updating status', but inside the Controller or inside the View $progress is always empty:

`$qj = $this->QueuedJobs->get($id);
debug($qj->progress);`

Any idea?

**Comment by dereuromark** [comment]
You need to manually update the progress from your task.
The task cannot know the progress automatically - see the example task https://github.com/dereuromark/cakephp-queue/blob/master/src/Shell/Task/QueueProgressExampleTask.php#L75
