### ISSUE TITLE
Job being fetched even if it was already fetched by previous worker

### ISSUE THREAD

**Issue by T0mi** [dereuromark/cakephp-queue#167]
Hi all,

I don't know if this is a feature or a bug or just a bad configuration but I have this problem. User is able to set defered job from frontend, nothing bad there. Job_type is set to _Execute_ and also the reference is being set so nothing special there either. It will execute command that's using custom Shell from cakephp. 

So the job that will be executed looks like `bin/cake my_shell my_action 'input'`

I have a cron, that will run worker every 5 minutes. The job that will be executed is heavy on load and will take approx from 20-60 minutes. Entry from queue is loading correctly and also the job is being executed correctly. The problem is that the next worker will also fetch the same job even if the job has already been fetched and has the workerkey assigned. So after that i have 2 workers handling the same job...

Is there some kind of workaround or am i using it wrong or is that expected behavior? The version I'm using is 3.7.0

Here is my config:

```
'Queue' => [
	'sleeptime' => 30,
	'gcprob' => 0,
	'defaultworkertimeout' => 3600,
	'defaultworkerretries' => 3,
	'workermaxruntime' => 3600,
	'cleanuptimeout' => 2592000,
	'exitwhennothingtodo' => true,
	'pidfilepath' => TMP . 'queue' . DS,
	'log' => true,
	'notify' => 'tmp',
	'mailerClass' => 'Cake\Mailer\Email'
]
```

**Comment by dereuromark** [comment]
You probbably skipped the part about timeout: https://github.com/dereuromark/cakephp-queue/tree/master/docs#task-configuration
This must be higher than this job could ever need to run. Otherwise it could be picked up while still running (and not reporting back in that time).

**Comment by T0mi** [comment]
Thanks for the fast reply! 

But I'm not using custom build queue task. I'm using default _Execute_ job type, so there's no way I could set that. I have my own shell in src/Shell that's being executed by cron every day but user can execute it if he needs to and that's when i'm using cakephp-queue.

**Comment by dereuromark** [comment]
We need to be able to pass the timeout then as payload.

**Comment by T0mi** [comment]
Yes, that would be great!

**Comment by dereuromark** [comment]
Otherwise just use custom commands or use one that has higher timeouts by default.
Closing then.
