### ISSUE TITLE
Support for Command Tasks

### ISSUE THREAD

**Issue by thumbtech** [dereuromark/cakephp-queue#168]
With announced deprecation of Shell and apparent migration to Command, I'm just curious to know (at a high level) how / when you plan on approaching this.

(I am a heavy user of Console\Shell as well as this plug-in and am a little freaked-out ... even though I know it is sticking around for the near future.)

Thanks

**Comment by JacobAGTyler** [comment]
Is there any update on this? How would one go about this if they were adding a PR.

**Comment by dereuromark** [comment]
I dont think there is a way to do that within 4.x without BC breaks
If you find one, you can PR it.
But otherwise we will just keep this until 5.x IMO.

**Comment by dereuromark** [comment]
Is someone interested in adding a command runner and deprecate the shell one?

If so, please also do the following
- Use a new stack of tasks now that are decoupled from communication layer (Shell/Command task), but independent
  E.g. `Queue/Task/` directly as namespace.
- Migrate existing tasks and deprecate also those then.

We could also make a major release and just remove the old way.

**Comment by dereuromark** [comment]
Two more things we should then change:

- It should also be possible to use FQCN::class for createJob() 
- and also now the full plugin syntax again: MyPlugin.MyTask (plugins and app do not interfere anymore then)
- we drop the Queue prefix as the namespace is already clear: App\Queue\Task\MyFooBarTask.php => MyFooBar

**Comment by dereuromark** [comment]
The hardest part will be to migrate the current nice dashboard/overview into the new (verbose and noisy) command structure:
```
Simple and minimalistic job queue (or deferred-task) system.

Available Tasks:
* AdminEmail
* CostsExample
* Email
* Example
* ExceptionExample
* Execute
* MonitorExample
* ProgressExample
* RetryExample
* SuperExample
* UniqueExample

Usage:
cake queue [subcommand] [-h] [-q] [-v]

Subcommands:

add         Add Job
clean       Remove old jobs (cleanup)
end         Manually end a worker.
hard_reset  Hard reset queue (remove all jobs)
kill        Manually kill a worker.
rerun       Manually rerun (successfully) run job.
reset       Manually reset (failed) jobs for re-run.
runworker   Run Worker
settings    Settings
stats       Stats

To see help on a subcommand use `cake queue [subcommand] --help`

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.
```

**Comment by dereuromark** [comment]
PR is now open: https://github.com/dereuromark/cakephp-queue/pull/276

Please contribute my adding your improvement ideas and feedback.
