### ISSUE TITLE
Email Queue Transport app.php config property not followed

### ISSUE THREAD

**Issue by michielkeijts** [dereuromark/cakephp-queue#169]
The QueueEmailTrask does not make use of the transport defined in app.php. E.g.: defining a transport in app.php for the Queue Transport does not work:

example:

````
'EmailTransport' => [
  'default' => [
            'className' => 'Mail',
            // The following keys are used in SMTP transports
            'host' => 'localhost',
            'port' => 25,
            'timeout' => 30,
            'username' => 'user',
            'password' => 'secret',
            'client' => null,
            'tls' => null,
            'url' => env('EMAIL_TRANSPORT_DEFAULT_URL', null),
        ],		
        'helpdesk' => [
            'className' => 'Office',
            // The following keys are used in SMTP transports
            'host' => 'smtp.office365.com',
            'port' => 567,
            'timeout' => 30,
            'username' => 'user',
            'password' => 'secret',
            'client' => null,
            'tls' => true,
            'url' => env('EMAIL_TRANSPORT_DEFAULT_URL', null),
        ],
		
		'queuedHelpdesk' => [
			'className' => 'Queue.Queue',
			'transport' => 'helpdesk'
		],
		'queuedDefault' => [
			'className' => 'Queue.Queue',
			'transport' => 'default'
		]
    ],
````

I am expecting that *queuedHelpdesk* does use transport *helpdesk* but it does not..  it uses the first element in the array: the default.

See line: https://github.com/dereuromark/cakephp-queue/blob/dba173c9e1e1a8c4cef826dc80d5a5557fec67fb/src/Shell/Task/QueueEmailTask.php#L81

## Solution:
This should be changed to: `$result = $email->setTransport($data['transport'])->send();`

**Comment by dereuromark** [comment]
Please make a PR.

**Comment by dereuromark** [comment]
Where did you get the idea that you can directly set transport here and it works?
Is that documented this way somewhere?

**Comment by michielkeijts** [comment]
I guess I would have read this in your readme files.. but.. Also by debugging your code after I got this bug in an production environment. 

The `setTransport` is a method of `Cake\Mailer\Email` and it is checked before if `$email` is an instance of `Email`..

Basically, I found that the default transport was used and updated and tested it. Works flawless now.
