### ISSUE TITLE
Get rid of dead status field?

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-queue#174]
Seems dead code.

Or does anyone still use it or know what it was for?

**Comment by PhantomWatson** [comment]
I was about to use it in a new application, actually. Here's my use case:
- User initiates a job, which takes a minute or so to complete, from the browser
- Job gets created and starts being processed in the background shortly thereafter
- As the job is being worked on, the task updates the `progress` and `status` fields of the job record
- The page that the user initiated the job from gets periodically updated with an advancing progress bar and text description of the current action being performed

**Comment by dereuromark** [comment]
Can u maybe document an example use case? That would help people see some value here.

**Comment by PhantomWatson** [comment]
Sure!
```php
class FooTask extends QueueTask
{
    public function run(array $data, $jobId)
    {
        // Initializing
        $jobsTable = \Cake\ORM\TableRegistry::getTableLocator()->get('QueuedJobs');
        $foo = new Foo();

        // Part one
        $jobsTable->updateAll(
            ['status' => 'Doing the first thing'],
            ['id' => $jobId]
        );
        $foo->dofirstPartOfTask();
        $jobsTable->updateProgress($jobId, 33);

        // Part two
        $jobsTable->updateAll(
            ['status' => 'Doing the next thing'],
            ['id' => $jobId]
        );
        $foo->donextPartOfTask();
        $jobsTable->updateProgress($jobId, 66);

        // Part three
        $jobsTable->updateAll(
            ['status' => 'Doing the last thing'],
            ['id' => $jobId]
        );
        $foo->dolastPartOfTask();
        $jobsTable->updateProgress($jobId, 100);

        // Done
        $jobsTable->updateAll(
            ['status' => 'Done doing things'],
            ['id' => $jobId]
        );
        
        return true;
    }
}
```

For me, the status field is the best way to give more detailed information about a long job than a progress bar alone can convey, which may help stave off user impatience.

**Comment by dereuromark** [comment]
All right.
We should just document this so far hidden feature somewhere.
Then we can close this.

**Comment by dereuromark** [comment]
Done :) Thanks for the feedback

**Comment by dereuromark** [comment]
You might be happy to hear that https://github.com/dereuromark/cakephp-queue/pull/190 also provides some status improvements.
