### ISSUE TITLE
QueuedJobsTable->getProcessed() doesn't take into account timezone

### ISSUE THREAD

**Issue by challgren** [dereuromark/cakephp-queue#182]
So I'm fairly new to CakePHP 3 and right now my server timezone and database timezone and app timezone are set to Central. When getting the processes that are running the QueueProcessesTable->findActive() passes time() - defaultworkertimeout to the query. However I'm guessing since an int is passed to the modified field the ORM is seeing it as a UTC timestamp when it is not a true UTC timestamp.

**Comment by dereuromark** [comment]
Are u able to provide a PR?

**Comment by challgren** [comment]
Let me see what I can do. I noticed it in a few other spots I think it would be best to convert the timestamp with date('Y-m-d H:i:s', $timestamp) what's your thoughts?

**Comment by dereuromark** [comment]
I agree :) And thank you.
