### ISSUE TITLE
Unknown column 'priority' when executing Queue.Queue runworker

### ISSUE THREAD

**Issue by savedario** [dereuromark/cakephp-queue#185]
This is only on the 2.x branch (I know...).

I tried to update the schema, but the column does not get created.
I also noticed the Config/Migration is in the branch, but I suspect that belongs with 3.x.
I ended up creating the column by end.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/blob/2.x/Config/Migration/1453822680_adding_priority_field_to_queue_tasks.php

Feel free to improve 2.x branch

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/pull/186
