### ISSUE TITLE
CakePHP 3.0

### ISSUE THREAD

**Issue by Laykou** [dereuromark/cakephp-queue#19]
This queue plugin would be great to have also for 3.0 version :+1:

**Comment by dereuromark** [comment]
Feel free to help out! :)

**Comment by Laykou** [comment]
Surely I would like to help. Do you think using the migration 2.x -> 3.0 for CakePHP is a good start? What should I keep in mind when trying to migrate this?

I'm working with CakePHP 3.0 for half a year but I don't find myself that much skilled.... anyway I would like to help to migrate this.

Just one more question: Is this plugin supposed to work also on Windows?

**Comment by dereuromark** [comment]
Hi there.
Yeah, the migration + the app for it.
Should work out. The tests should pass afterwards, again.

Yes it also works on Windows, there you cannot use crontab though but need some other tool for it if you want to really use it. For debugging its fine either way.

**Comment by Laykou** [comment]
I can use the *Windows Scheduled tasks*. Do find it to be a good idea to use cake and also other repeating shell tasks via *Windows Sheduled tasks*?

**Comment by dereuromark** [comment]
I never tried. Try it an share your experiences.

**Comment by zoghal** [comment]
@Laykou can try this utility's on windows :
http://cronsm.sourceforge.net/
http://sourceforge.net/projects/batchrunner/

**Comment by gabehesse** [comment]
How do I run the tests on this project?  Sorry new to PHP but not programming, this is not obvious or documented.

When I run the PHP upgrade utility I get this output:

Welcome to CakePHP v3.0.0 Console
---------------------------------------------------------------
App : src
Path: /Users/gabe.hesse/dev/php/upgrade/src/
---------------------------------------------------------------
*** Upgrade step Locations ***
*** Upgrade step Namespaces ***
*** Upgrade step AppUses ***
CakeSchema is not in the implicit class map
CakeSchema is not in the implicit class map
QueueEmailTask is not in the implicit class map
ClassRegistry is not in the implicit class map
QueueController is not in the implicit class map
QueuedTask is not in the implicit class map
RegexIterator is not in the implicit class map
AbstractTransport is not in the implicit class map
CakeEmail is not in the implicit class map
ClassRegistry is not in the implicit class map
PHPUnit_Framework_TestSuite is not in the implicit class map
PHPUnit_Framework_TestSuite is not in the implicit class map
PHPUnit_Framework_TestSuite is not in the implicit class map
PHPUnit_Framework_TestSuite is not in the implicit class map
QueueShellTest is not in the implicit class map
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in upgrade/vendor/cakephp/cakephp/src/TestSuite/TestCase.php on line 28

Fatal error: Class 'PHPUnit_Framework_TestCase' not found in upgrade/vendor/cakephp/cakephp/src/TestSuite/TestCase.php on line 28

**Comment by dereuromark** [comment]
I think you are confused. This is a ticket about migrating the 2.x code to 3.x. It has not happened yet. There is no way to test it using CakePHP 3 classes yet.
You test this code as outlined in the travis.yml file - by added it into an app and running the plugin tests.

**Comment by dereuromark** [comment]
Almost done. Please help on finalizing it and testing it in 3.x :)

**Comment by zoghal** [comment]
:+1:  good work, i start to use this
