### ISSUE TITLE
Fatal error: Class 'App\Shell\Task\QueueTask' not found

### ISSUE THREAD

**Issue by uemit24** [dereuromark/cakephp-queue#197]
hello!

I installed your plugin and wanted to test it, and created my own Task in the /src/Shell/Task/ directory as instructed. I copied your example as seen in your docs, here is my Example Task "Reminder":

namespace App\Shell\Task;

class QueueReminderTask extends QueueTask {

	public function run(array $data, $jobId) {
		$this->loadModel('FooBars');
		if (!$this->FooBars->doSth()) {
			throw new RuntimeException('Couldnt do sth.');
		}

		return true;
	}
	
}

and now when I run  "bin/cake queue runworker" I´m getting the following error:

Fatal error: Class 'App\Shell\Task\QueueTask' not found in /var/www/src/Shell/Task/QueueReminderTask.php on line 6

Could you please provide some advice? 
Thank you very much

**Comment by dereuromark** [comment]
Well, it tells you exactly what you need to fix: You forgot a basic PHP thing: The used (extended) Queue Task needs to be included (as do all other tasks if you look into them):

    use ...

**Comment by uemit24** [comment]
I knew its going to be obvious for you. I´m usually not a developer and still learning. Thank you very much!

**Comment by dereuromark** [comment]
Sure, but please note that this is an issue tracker for bugs and enhancements.
The support forums are there for this kind of help (IRC Channel, Forum etc)
