### ISSUE TITLE
Plugin not found during Testing

### ISSUE THREAD

**Issue by challgren** [dereuromark/cakephp-queue#205]
So I'm working on more tests for my app and when testing my afterSave function that creates a QueuedJob I'm presented with a `Plugin Queue could not be found.`

Table:afterSave()
```
$queue = TableRegistry::getTableLocator()->get('Queue.QueuedJobs');
$queue->createJob('AuditStatusChange', $data);
```

config/app.php
```
return [
    'Queue' => [
        'gcprob' => 10,
        'cleanuptimeout' => 60 * 60 * 24 * 30,
        'workermaxruntime' => 60 * 15,
    ],
];
```

StackTrace
```
Cake\Core\Exception\MissingPluginException: Plugin Queue could not be found.

/vendor/cakephp/cakephp/src/Core/PluginCollection.php:194
/vendor/cakephp/cakephp/src/Core/Plugin.php:269
/vendor/cakephp/cakephp/src/Core/Configure/FileConfigTrait.php:52
/vendor/cakephp/cakephp/src/Core/Configure/Engine/PhpConfig.php:86
/vendor/cakephp/cakephp/src/Core/Configure.php:343
/vendor/dereuromark/cakephp-queue/src/Model/Table/QueuedJobsTable.php:136
/vendor/dereuromark/cakephp-queue/src/Model/Table/QueuedJobsTable.php:91
/vendor/cakephp/cakephp/src/ORM/Table.php:298
/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php:257
/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php:224
/src/Model/Table/EnergyAuditsTable.php:275
/tests/TestCase/Model/Table/EnergyAuditsTableTest.php:125
```

However if I add `'configLoaded' => true` to my `app/config.php` the error goes away.

**Comment by dereuromark** [comment]
How did you load the Queue plugin?

**Comment by challgren** [comment]
In `/src/Application.php` via `$this->addPlugin('Queue', ['routes' => false]);`

**Comment by challgren** [comment]
Using dev-master and CakePHP 3.7.1

**Comment by dereuromark** [comment]
Could it be because Plugin.php is missing yet?

**Comment by dereuromark** [comment]
Can you please try latest master? I added that file now. Sounds like an issue with core then.

**Comment by challgren** [comment]
Nope still happening

**Comment by dereuromark** [comment]
So yeah, looks like this requires `Queue.configLoaded` set to true and made sure no Configure::load() call (deprecated) is invoked.

**Comment by dereuromark** [comment]
For now documented in https://github.com/dereuromark/cakephp-queue/commit/5be853615b5e7a637c2cd89cbd049e6cc68bf655
