### ISSUE TITLE
Processes problems with new pid constraint/key

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-queue#210]
> [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-heroku-app' for key 'pid' in /app/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php on line 39

Is now thrown now every time a worker is started.
is the process pid always 4 here? it seems so.. maybe we need to do sth different then.

**Comment by garas** [comment]
Probably Heroku doesn't have `posix_getpid()` at all and always used `$this->QueuedJobs->key()`, and `getmypid()` on Heroku returns hard coded value. Everywhere I've checked both functions returns same value if `posix_getpid()` exists. I don't have access to Heroku to check these things.

Maybe I will look why `bin/cake queue end` didn't work on Windows when it used sha1 key.

**Comment by garas** [comment]
I think `QueueProcesses.pid` could be dropped and always use sha1 `QueueProcesses.workerkey` as process identifier.

Some other systems could have `posix_getpid()` with hardcoded PID and could have the same problem.

**Comment by dereuromark** [comment]
I agree for the identification of the running jobs. Still dont want to keep pid though if one manually wants to look into the server and kill them by hand.

**Comment by garas** [comment]
Unique index on `(pid, server)` could be dropped as it has problems after unclean exits / external kill. After this, `getmypid()` could be re-added.

`pid` should be left for killing purposes only, everywhere else `workerkey`  or `id` should be used.

**Comment by dereuromark** [comment]
Are you able to help out here maybe?

**Comment by garas** [comment]
Yes, I'll try to implement this.

**Comment by dereuromark** [comment]
Any update here? Or can I help?

**Comment by garas** [comment]
I did not have enough free time to look at this. I'm not sure if I'll be to help here in next few weeks, sorry.

**Comment by dereuromark** [comment]
For now unique of pid+server seems to suffice even for heroku and multi-server use cases it seems.
Just needs a unique server name set up here.
