### ISSUE TITLE
Add a couple of callbacks before/after running a QueueTask

### ISSUE THREAD

**Issue by savedario** [dereuromark/cakephp-queue#216]
I am implementing an application with 2 database and since all QueueTasks instances are created when the worker starts, I bumped into the problem that the connection to the second database, where there are no Queue-related tables, closes for timeout.
All my QueueTasks are derived from an AppQueueTask class that has the common code.
I suggest to add a couple of callbacks: beforeRun() and afterRun() that are automatically called by QueueTask::runworker() before and after calling the run() method.
I will submit a pull request if this is useful, otherwise I will fork the repository.
This for the 2.x branch... and I don't have capacity to port it to 3.x for a while...

**Comment by dereuromark** [comment]
2.x is in maintenance mode. Please fork here.

But it would be nice if u could report the changes here (link to pr), so i can see what i can port to 3.x.
