### ISSUE TITLE
Run code after queue failed x times

### ISSUE THREAD

**Issue by doonot** [dereuromark/cakephp-queue#222]
Thanks for this cool plugin. I started to implement it into our application and also the docs are pretty good. 

I am now wondering if it is possible to run specific code after the queue retried x times and failed. I would like to be able to send an email if the queue retried 5 times without success.

Is there something built in or should I look for the database status regularly?

Thanks and regards, Pat

**Comment by dereuromark** [comment]
Such logic sounds like something custom you might want to build on top.
