### ISSUE TITLE
Object of class Cake\I18n\FrozenTime could not be converted to int 

### ISSUE THREAD

**Issue by lorro** [dereuromark/cakephp-queue#224]
Hi Mark,

I've been using your plugin on a couple of apps already, and this is the first time I'm trying to use the admin routes. But I'm getting an error when surfing to the admin/queue route.

I'm getting this error on line 234 of QueueProcessesTable.php
```php
if ($time >= $thresholdTime) {
  $count++;
}
```

$tresholdTime is a FrozenTime object
$time is a plain numeric timestamp. So I guess it can't compare.

Do you have any idea how we could fix this?
Thanks

**Comment by dereuromark** [comment]
Ah, that part is long deprecated - the newer versions are mainly using the DB instead of file system.
Please try to upgrade here.

You can, however, also provide a small fix to do a ->toUnixTimestamp() etc to be able to use the current old behavior. As a PR then please.

**Comment by lorro** [comment]
Oh ok.
I already pulled in the latest version of the plugin though.

But setting `'pidfilepath' =>  false` had solved my issue.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/commit/914bc5acaeac642c196e49d3bc5f53cfc7edc700 should fix it.
