### ISSUE TITLE
Installing plugin on Cakephp 3.5

### ISSUE THREAD

**Issue by SandHoofd** [dereuromark/cakephp-queue#227]
Hi,

I want to install this plugin on cakephp 3.5. I saw on[ this ](https://github.com/dereuromark/cakephp-queue/wiki) page that I can use plugin version 3.x, but when I try to install I get a non compatibility error. 

Which version do I need for cakephp 3.5?

**Comment by dereuromark** [comment]
composer require as documented will tell you what version is compatible.
