### ISSUE TITLE
Two Process pick same task

### ISSUE THREAD

**Issue by ashish-k-shah** [dereuromark/cakephp-queue#229]
Hello,

I implemented this plugin in a project. But after implementation found that, two processes simultaneously pick up the same task.

Can you please advise how I avoid this situation.

**Comment by dereuromark** [comment]
How did that happen? Did you have a too small timeout? 
Also what DB and plugin version are you using?

**Comment by ashish-k-shah** [comment]
I set an interval of 7min.  Used Mysql as DB.

**Comment by dereuromark** [comment]
And how long is the job running? Mysql must use InnoDB for transaction-safe access.

**Comment by ashish-k-shah** [comment]
Job hardly take 15-20 sec for execution. DB engine type is InnoDB. Do I need to do some additional settings for this? 

Also, the queue process created through CronJob which is never closed once finished the current job. Is this creates a problem? Let me know. 

If yes, then can you please provide me a solution. I need to run a process in background for immediate execution of a task in Queue is pending.

**Comment by dereuromark** [comment]
No, that is all how it is supposed to be.
Try running only single worker for now. Also check docs for multi-server setup etc if you have sth like this.

This must be some config issue on your side.

**Comment by ashish-k-shah** [comment]
Hi,

I used below configuration:
        'workermaxruntime'     => 1600,
        'sleeptime'            => 15,
        'gcprob'               => 15,
        'defaultworkerretries' => 3600,
        'cleanuptimeout'       => 2592000,
        'exitwhennothingtodo'  => false,
        'defaultworkerretries' => 0,
        'log'                  => true,
        'notify'               => 'tmp',
        'mailerClass'          => 'Cake\Mailer\Email',

Is that something wrong I added here. Let me know so I can correct it.

**Comment by dereuromark** [comment]
No, should all be fine. It sure is for all of us others using it now for months.
Again: What version are you using?

**Comment by ashish-k-shah** [comment]
Using Cake 3.2 with plugin 3.4.1. So do I need to update this queue plugin? Let me know.

**Comment by dereuromark** [comment]
You should be using 3.16+
Everything else is possibly not safe to use.
