### ISSUE TITLE
[Question] Compatibility with cakephp 3 

### ISSUE THREAD

**Issue by flashios09** [dereuromark/cakephp-queue#23]
Hi @dereuromark ,
sorry for my bad english :(
i have a stupid question, can i use this plugin with **cakephp 3** ? if i can't, will you migrate it ? 
thanks

**Comment by dereuromark** [comment]
You can help migrate it :) Currently I do not have the time for it.

**Comment by dereuromark** [comment]
See https://github.com/dereuromark/cakephp-queue/issues/19

**Comment by flashios09** [comment]
@dereuromark , 
thanks for your quick response ;)
i'm new with cakephp 3, i will try to migrate it but i don't think that i have the skills to do it :(
