### ISSUE TITLE
Before retry the failure job it starts throwing 'nothing to do'

### ISSUE THREAD

**Issue by Agalya05** [dereuromark/cakephp-queue#238]
Before retry the failure job it starts throwing 'nothing to do' until it reach the job $timeout = 120;
[2019-09-05 04:38:30] Looking for Job ...
nothing to do, sleeping.
---------------------------------------------------------------
[2019-09-05 04:38:35] Looking for Job ...
nothing to do, sleeping.
..... 

How can I avoid the printing the "nothing to do, sleeping." message until it completes the maximum retry or the  job success.

My task based queue configuration
*    public $timeout = 10;
*    public $retries = 4;

My application based app_queue configuration
	'Queue' => [
		'workermaxruntime' => 60,
                'sleeptime' => 2,
		'maxworkers' => 5,
		'defaultworkerretries' => 5,
	],

**Comment by dereuromark** [comment]
Retry has a timeout, that is a normal thing. What is the issue?

**Comment by Agalya05** [comment]
So until the timout and before retry will it keep throw the "nothing to do, sleeping." message ?

**Comment by dereuromark** [comment]
Check the code and query, why it waits. This will give some answers.
But often this is useful as the network connection for emails etc might need a bit to recover.

**Comment by Agalya05** [comment]
Ok. I thought there will option to retry before throwing "Nothing to Do". Thanks for your clarification.

**Comment by dereuromark** [comment]
You can check. But for now the queue checks if sth else can be done in the meantime.
Thats why you are seeing this message.

**Comment by dereuromark** [comment]
Please check your

    public $timeout = [int];

This will usually play into the min seconds to wait until it will be looked into for re-run.
