### ISSUE TITLE
Job getter query is very slow on large datasets

### ISSUE THREAD

**Issue by mfrascati** [dereuromark/cakephp-queue#243]
Hi there, I'm using the plugin for an email sending service, sending over 70k mails per day, and I found out that on this scale the query for getting jobs is quite slow, needing more than 1 second to retrieve the next job to process.

After some query debugging I found out that the biggest responsible for the slowdown is the `SELECT (IFNULL(TIMESTAMPDIFF(SECOND, "2019-09-18 03:19:13", notbefore), 0)) AS age` as well as the `ORDER BY age ASC` part, which cannot be indexed and needs recalculation all the time. Without this part the query takes less than 200ms (prev time 1.5s).

I understand this part is required to prioritize task execution, but this slowness is making the queue pretty useful. Do you have any ideas of how this could be optimized?

(Plus, non that really slowing but in the query are included all OR conditions for the Example tasks provided by the plugin samples, which share the same namespace with the user tasks but clearly will never be used: maybe there could be a way to filter them out in the query building?)

**Comment by dereuromark** [comment]
Feel free to provide a PR with suggested Improvements. 
I am not sure how we could calculate the prio otherwise.

**Comment by michielkeijts** [comment]
This is still an issue right? Is or was there any reason to `SELECT` and `ORDER BY age` versue a simple `order by notbefore`? It seems that will give the desired result. 

Also: `notbefore` could be changed from NULLABLE to NOT NULLABLE and give the default value `NOW()` to improve indexation

Just wondering if this could help. I could put this into a PR

**Comment by mfrascati** [comment]
Not sure setting it to NOW would fix the issue because it will prioritize tasks with `not_before = NULL`. If I'm correct, as of now a task with a `not_before < NOW` should have priority over one with `not_before = NULL`.

I wasn't able to figure out a solution on how to speed up this, but I solved my problem by chunking tasks, storing 5 ids instead of 1, and accepting the tradeoff that 1 failing job causes the entire chunk to fail.
