### ISSUE TITLE
problem when using $this->QueuedJobs->createJob() in controller

### ISSUE THREAD

**Issue by dangdhh** [dereuromark/cakephp-queue#244]
i run queue in command ok.
but i put $this->QueuedJobs->createJob() in controller and call api error

![image](https://user-images.githubusercontent.com/27469494/65593600-05c22a00-dfbb-11e9-9e67-ae6387448d64.png)

**Comment by dereuromark** [comment]
You are using SQLite DB?

**Comment by dangdhh** [comment]
> You are using SQLite DB?
> This is a Cake config error or dev error, not related to the plugin itself IMO.

yeap . i using mySQL . but i run bin/cake migrations migrate -p Queue . the table created ok . and run command bin/cake queue add , bin/cake queue runworker is ok . and then .i put this code  $this->QueuedJobs->createJob() in controller and call api error

**Comment by dereuromark** [comment]
Did you do what the message tells you? Enabling identifier quoting?

**Comment by dangdhh** [comment]
![image](https://user-images.githubusercontent.com/27469494/65681041-636d7980-e082-11e9-9cfe-75774cd3bd08.png)
but not work :(

**Comment by dereuromark** [comment]
This doesnt look like an issue with the plugin, but rather with your app/code/setup.

**Comment by dangdhh** [comment]
i setup addPlugin is that right ?
![image](https://user-images.githubusercontent.com/27469494/65681285-c0692f80-e082-11e9-9cb9-f17efe86db8a.png)

**Comment by dereuromark** [comment]
No

a) never add plugin twice
b) never add a plugin to CLI only when it is clearly needed also for non-CLI (=web).
