### ISSUE TITLE
Event, Trigger after run queue failed xx times

### ISSUE THREAD

**Issue by dangdhh** [dereuromark/cakephp-queue#245]
i have a problem . After run queue retries xx  times . i want to send mail for user. 

Is there something (event, trigger) built in or should I look for the database status regularly?
please for me example . thank so much

**Comment by dereuromark** [comment]
What do you propose we add here? Feel fee to make a PR with suggested changes.

**Comment by dangdhh** [comment]
where should i put function send mail after run queue retries xx times. ? plz help me
