### ISSUE TITLE
Admin session checking

### ISSUE THREAD

**Issue by ashish-k-shah** [dereuromark/cakephp-queue#248]
Hello,

I am using admin panel but want to check session of my custom session of admin.

How can I do that?

**Comment by dereuromark** [comment]
What do you mean?
What is your "custom session of admin."?

Please provide a bit more detailed report.

**Comment by ashish-k-shah** [comment]
I have an admin panel that is created by own plugin and managed session there. I do not want to allow access to an admin of the queue directly.

How can I do this?

**Comment by dereuromark** [comment]
Then your plugin should not expose that as public.
You have the Auth component enabled? This protects then by design.

Tip: [TinyAuth](https://github.com/dereuromark/cakephp-tinyauth) is the best choice for super simple auth solution.

**Comment by ashish-k-shah** [comment]
Thanks for the information.
