### ISSUE TITLE
Can't use custom APP task with same name as one in Queue plugin

### ISSUE THREAD

**Issue by houseoftech** [dereuromark/cakephp-queue#25]
I tried to copy the QueueEmailTask.php to my App so I could make my own custom email task, but it keeps running the plugin version.

In [QueueShell::initialize()](https://github.com/dereuromark/cakephp-queue/blob/master/Console/Command/QueueShell.php#L44-63) if you switch around the searching of the tasks such that APP tasks are loaded after plugins, then the app version would override the plugin version and it works.

I'm not sure if this is a big enough deal for you to want to make the change. I just thought I'd point it out.

**Comment by dereuromark** [comment]
Are you sure it reverts the order? Can't find that part in there.
The quick solution would be to name it differently, I guess.

**Comment by houseoftech** [comment]
At line 44 you would change

````
		foreach ($paths as $path) {
			$Folder = new Folder($path);
			$res = array_merge($this->tasks, $Folder->find('Queue.*\.php'));
			foreach ($res as &$r) {
				$r = basename($r, 'Task.php');
			}
			$this->tasks = $res;
		}
		$plugins = CakePlugin::loaded();
		foreach ($plugins as $plugin) {
			$pluginPaths = App::path('Console/Command/Task', $plugin);
			foreach ($pluginPaths as $pluginPath) {
				$Folder = new Folder($pluginPath);
				$res = $Folder->find('Queue.*Task\.php');
				foreach ($res as &$r) {
					$r = $plugin . '.' . basename($r, 'Task.php');
				}
				$this->tasks = array_merge($this->tasks, $res);
			}
		}
````
to
````
		$plugins = CakePlugin::loaded();
		foreach ($plugins as $plugin) {
			$pluginPaths = App::path('Console/Command/Task', $plugin);
			foreach ($pluginPaths as $pluginPath) {
				$Folder = new Folder($pluginPath);
				$res = $Folder->find('Queue.*Task\.php');
				foreach ($res as &$r) {
					$r = $plugin . '.' . basename($r, 'Task.php');
				}
				$this->tasks = array_merge($this->tasks, $res);
			}
		}
		foreach ($paths as $path) {
			$Folder = new Folder($path);
			$res = array_merge($this->tasks, $Folder->find('Queue.*\.php'));
			foreach ($res as &$r) {
				$r = basename($r, 'Task.php');
			}
			$this->tasks = $res;
		}
````

**Comment by dereuromark** [comment]
Why? Wouldnt that make exaxtly what you didnt want? To have plugins before app?

**Comment by houseoftech** [comment]
If the app task is loaded after the plugin version it will be the one that is available. It basically overwrites it.

**Comment by dereuromark** [comment]
I see. Well, names in 2.x need to be unique througout the app. So it will eventually fail anyway.
So better to stay unique.
