### ISSUE TITLE
4.x: Finish beta release

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-queue#251]
Some important tests are still failing that block CakePHP 4..x compatible beta release

Also:
- Email/Mailer functionality

**Comment by lpj145** [comment]
You know when be ready ? need help ?

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/releases/tag/5.0.0-rc should be tested and confirmed.
Then we can release the stable one.

**Comment by dominicwild** [comment]
Any estimate on when a stable one will be released? As I have a project I'd like to use this on, but it doesn't work with CakePHP 4 to my knowledge yet?

**Comment by dereuromark** [comment]
It does. the beta and RC is long out.
But someome still needs to confirm this linked last release to say all is working well.

**Comment by lpj145** [comment]
> 
> 
> It does. the beta and RC is long out.
> But someome still needs to confirm this linked last release to say all is working well.

you simple need extreme tests on 4x ?

**Comment by dereuromark** [comment]
Well, some more detailed than my smoke tests :)
