### ISSUE TITLE
maxworker limit per type or group

### ISSUE THREAD

**Issue by busgurlu** [dereuromark/cakephp-queue#254]
Ability to run specific tasks per worker is great. However it is also limited by the global maxworkers setting. I couldn't find a way to specify a maxworker limit specific to the type or group.

Ex.: 2 workers for type A jobs, 1 worker for group B, etc.

Would anyone be interested in such a feature? I'm willing to add it. Or am I missing some other way to accomplish this?

**Comment by dereuromark** [comment]
You can try to implement this.
But keep in mind that the query is already quite complicated/long, and thus slow for larger DB tables.
We might not want to further slow this down. Maybe there is a way to do this without this drawback, though.

**Comment by busgurlu** [comment]
I ended up listening to beforeFind of QueuedJobs and inserted some logic there. It is quite complex to filter out the specific query and modify the query like this and would likely break with an update. Perhaps an injection point can be set somewhere similar and would be helpful to expose some of the options for the query directly.

**Comment by dereuromark** [comment]
Ok, then we can close.
