### ISSUE TITLE
Bug while using the queue transport in 5.x

### ISSUE THREAD

**Issue by allanmcarvalho** [dereuromark/cakephp-queue#257]
2020-03-30 06:09:12 Info: job Email, id 24241 (pid 33718)
Warning Error: array_merge(): Expected parameter 2 to be an array, object given
In [/Users/allancarvalho/Desenvolvimento/GitHub/email-sender/vendor/dereuromark/cakephp-queue/src/Shell/Task/QueueEmailTask.php, line 114]

2020-03-30 06:09:12 Warning: Warning (2): array_merge(): Expected parameter 2 to be an array, object given in [/Users/allancarvalho/Desenvolvimento/GitHub/email-sender/vendor/dereuromark/cakephp-queue/src/Shell/Task/QueueEmailTask.php, line 114]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 188
array_merge - [internal], line ??
Queue\Shell\Task\QueueEmailTask::run() - ROOT/vendor/dereuromark/cakephp-queue/src/Shell/Task/QueueEmailTask.php, line 114
Queue\Shell\QueueShell::runJob() - ROOT/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php, line 266
Queue\Shell\QueueShell::runworker() - ROOT/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php, line 214
Cake\Console\Shell::runCommand() - CORE/src/Console/Shell.php, line 502
Cake\Console\CommandRunner::runShell() - CORE/src/Console/CommandRunner.php, line 354
Cake\Console\CommandRunner::run() - CORE/src/Console/CommandRunner.php, line 168
[main] - ROOT/bin/cake.php, line 12

Warning Error: Invalid argument supplied for foreach()
In [/Users/allancarvalho/Desenvolvimento/GitHub/email-sender/vendor/dereuromark/cakephp-queue/src/Shell/Task/QueueEmailTask.php, line 127]

2020-03-30 06:09:12 Warning: Warning (2): Invalid argument supplied for foreach() in [/Users/allancarvalho/Desenvolvimento/GitHub/email-sender/vendor/dereuromark/cakephp-queue/src/Shell/Task/QueueEmailTask.php, line 127]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 188
Queue\Shell\Task\QueueEmailTask::run() - ROOT/vendor/dereuromark/cakephp-queue/src/Shell/Task/QueueEmailTask.php, line 127
Queue\Shell\QueueShell::runJob() - ROOT/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php, line 266
Queue\Shell\QueueShell::runworker() - ROOT/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php, line 214
Cake\Console\Shell::runCommand() - CORE/src/Console/Shell.php, line 502
Cake\Console\CommandRunner::runShell() - CORE/src/Console/CommandRunner.php, line 354
Cake\Console\CommandRunner::run() - CORE/src/Console/CommandRunner.php, line 168
[main] - ROOT/bin/cake.php, line 12

**Comment by allanmcarvalho** [comment]
The code expect the $data['settings'] as array, but it is a Mailer/Message

**Comment by dereuromark** [comment]
what version of the plugin?
and can you make a PR that fixes it?

**Comment by allanmcarvalho** [comment]
I tried on RC and on master... Both have the same problem. I am trying to fix, but I believe that the problem can be on Core. On QueueTransport class, in the method send the param \Cake\Mailer\Message $message don't have a message body. Is empty!

On QueueEmailTask Class, we can fix the problem putting a new if "if (is_object($mailerOrMessage) && $mailerOrMessage instanceof Message) {...". I believe that this will fix the problem. But the message still without body....

What you suggest?

**Comment by dereuromark** [comment]
Maybe you can show me your code and I try to reproduce it.

**Comment by allanmcarvalho** [comment]
I deleted it :(.

But it was simple and clean. I downloaded the CakePHP app, I installed your plugin, and after I baked a mailer with layout and template file. On email preview it show normally, and when without queue it send. But when I use the queue for send, exactly as I used other times, and the way that is requested in the documentation, the above error appear. 
I am using the MAMP PRO 5.7 server with PHP 7.4.2 on MacOs.

**Comment by gludie** [comment]
Hi there, was closed to send you an email but luckily quickly checked the issues: I have the same issue, and can provide some code snippets. I think it happens when using a custom mailer ...

the standard queuing is working so far (input), but then in the task ( worker ) it checks if the passed data['settings'] is an object and instance of mailer, but will not enter this if, cause it is instance of Cake/Mailer/Message. ?
the full mailer object is available in settings, but there is no seperation of content e.g.

I think, this happens, if you just change the config, which might work, if you send simple mails with Mailer already ... but if you use e.g.
                
> $this->getMailer('User')
>                     ->send('sendorder', [$viewVars]);
> 

and in e.g. usermailer:

>         $this
>             ->setTo('abc@cxy.com')
>             ->setSubject('Your order (' . $vars['order']->id . ')')
>             ->setAttachments([$filename])
>             ->viewBuilder()->setTemplate('sendorder');
> 

then you get the exception&warning in 115/128 in QueueMailTask.php.

**Comment by dereuromark** [comment]
I see. Yeah, we could either add a specific Task that can handle the mailer object
Or we document that the data should rather be send as config, and the final object is assembled then only in the cli queue task itself always.

**Comment by dereuromark** [comment]
Wait, it supports Mailer already.
Are you actually sending it in the controller already? send()?
That you shouldn't do, but pass it on to the Queue already before that.

**Comment by gludie** [comment]
correct, you are right, I am using getMailer(..) in the Controller to produce the content for a specific template (very similar to the cake documentation of Mailer). 

it would be really better to refactor the code, so that UserMailer efforts, where also the attachments for the mail are produced (time consuming), are performed in the task. definitely the better approach when already going for background processing ... so putting just references and actiontypes into the queue and let it got ... 

I try to provide an example soon and lets check if it is worth to add some hints in the doc
dealing with attachments, etc. ...

**Comment by dereuromark** [comment]
With my last commit it should now work fully: https://github.com/dereuromark/cakephp-queue/commit/cd3dc4dc36c9f1c2f004c7fa4bcf0ec4993b3e10

I did the following test:
```
        $mailer = $this->getMailer('User');
        $mailer->viewBuilder()
            ->setTemplate('demo');
        $mailer->setFrom('...');
        $mailer->setTo('...');
        ...

        $this->loadModel('Queue.QueuedJobs')->createJob(
            'Email',
            ['settings' => $mailer]
        );
```

**Comment by dereuromark** [comment]
Also added a bit more docs https://github.com/dereuromark/cakephp-queue/commit/32adbf639812570f0372cd4bf7687965fbaaf652

**Comment by gludie** [comment]
nice solution ! just putting the whole mailer to settings ... thanks a lot ... will test soon ... and only want to say, that your advise in the doc is more than valid, cause producing pdf attachments for mails is often consuming more time than sending mails ;-) ... so even more a reason to have only a short queue put in the controller and the rest is in the worker ... but for quick tests this capability now is super for simple email tests ... thx again for fast support
