### ISSUE TITLE
Queue Configuration Issue

### ISSUE THREAD

**Issue by ashish-k-shah** [dereuromark/cakephp-queue#262]
Hello,

I have AWS server with ELB configuration. I want to run queue in background for only one instance.

Currently its running for all the instances.

is there any configuration available for this setup?

Lt me know.

**Comment by dereuromark** [comment]
I am not familiar with this kind of setup. But if you can control the crontab tool then you should be able to also conditionally do that per env config for example.

The invocation of the runner is not part of this plugin, this is part of the OS.
