### ISSUE TITLE
Add multiple to(addTo) email id

### ISSUE THREAD

**Issue by veera1908** [dereuromark/cakephp-queue#263]
**is possible add multiple to email id in the below code** 
$data = [
    'settings' => [
        'to' => $user->email,
        'from' => Configure::read('Config.adminEmail'),
        'subject' => $subject,
    ],
    'content' => $content,
];
$queuedJobsTable = TableRegistry::getTableLocator()->get('Queue.QueuedJobs');
$queuedJobsTable->createJob('Email', $data);

**Comment by dereuromark** [comment]
I am not sure, feel free to make a PR here if you find a solution.
Otherwise maybe you can pass the object itself.

**Comment by dereuromark** [comment]
Tests added show that it works: https://github.com/dereuromark/cakephp-queue/commit/f121948336814c8614282969b44fa73fd40ac55a
Feel free to make any docs improvement here.
