### ISSUE TITLE
Support for debug?

### ISSUE THREAD

**Issue by infokani** [dereuromark/cakephp-queue#266]
Am I using it right? and how do I debug?

QueuePostNotifyTask.php

```
<?php

namespace App\Shell\Task;

use Queue\Shell\Task\QueueTask;

class QueuePostNotifyTask extends QueueTask
{

	/**
	 * @param array $data Payload
	 * @param int $jobId The ID of the QueuedJob entity
	 * @return void
	 */
	public function run(array $data, int $jobId): void
	{
	       $this->loadModel('Notifications');
               $notification = $this->Notifications->newEmptyEntity();
               $notification->text = $data['text'];
               $this->Notifications->save($notification)
	}
}
```

PostsController.php

```
        $this->loadModel('Queue.QueuedJobs');
        $this->QueuedJobs->createJob(
            'PostNotify',
            ['text' => "some text"]
        );
```

**Comment by dereuromark** [comment]
You usually write test cases for this class/method and this way test it before you use it
Then you invoke it for real. You can alternatively keep debug on, and debug enabled and step through it when manually running the queue worker.

So whats the issue here? This is a bugtracker.

**Comment by infokani** [comment]
Just nothing happen. seems task not running

**Comment by dereuromark** [comment]
How are you running the worker?
You need to provide more details or otherwise this is not possible for me to help.

**Comment by infokani** [comment]
Thanks. It works perfect but I misunderstood its usage. I thought it run code block like async.
