### ISSUE TITLE
Running into issues when running cake queue runworker

### ISSUE THREAD

**Issue by delatopa** [dereuromark/cakephp-queue#267]
When trying to run `cake queue runworker` I am encountering the following message:
```
Entity save failure. Found the following errors (server.validateCount: "Too many workers running.").
Cannot start worker: Too many workers already/still running on this server (3/3)
```

When I run `cake queue stats` it states I am not running any workers: 
```
Running workers (processes): 0
```

Wanted to see if there is any insight on what else I can check?  Thank you in advance.

**Comment by dereuromark** [comment]
You have zombie processes in the table. Clear them.
