### ISSUE TITLE
Test report from migrating from 5.x -> 6.x

### ISSUE THREAD

**Issue by HarderWork** [dereuromark/cakephp-queue#278]
I have only 3 Tasks, they all work well after migrating to 6.0.0-alpha.

A couple of things I noticed (I don't expect any feedback, so just ignore if you want to :) )

1.
Docs say 

Then run `composer migrate -p Queue` to migrate DB schema.

Shouldn't it be:
`bin/cake migrations  migrate -p Queue`

2.
When tasks was in src/Shell/Task, I could use
`$this->getTableLocator()->get('MyTable');`

When moving to src/Queue/Task I need to use
`use Cake\ORM\TableRegistry;`
`TableRegistry::getTableLocator()->get('MyTable');`

**Comment by dereuromark** [comment]
You are right, fixed the docs part

The Task itself uses ModelAwareTrait
So all those should be changed to 

    $this->loadModel('MyFooBar');
    $this->MyFooBar->

etc

I wonder if we should add the table locator instead, so the code itself doesn't need to change.
Feel free to make such PRs if you think it is better than using the ModelAwareTrait
