### ISSUE TITLE
RFC - Dependencies between planned tasks

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-queue#280]
I have seen in other queue systems that especially planned tasks can have a dependency system integrated.

This means, that e.g. `Task B` planned for tomorrow 02:00:00 can't be executed till `Task A` planned for 20:00:00 today is done.

I wouldn't say this is somewhat needed for non-planned tasks but I guess it wouldn't make a huge difference.

What are your thoughts on this?

**Comment by dereuromark** [comment]
Dependencies between different tasks seems not doable as the query would be too complex.
Right now you can kind of do it using time offsets (delay a >> delay b).

If you have ideas on how to achieve more, let me know.
So far, I don't think this is possible using such a basic DB query system.
This would require a more sophisticated queueing system then.

**Comment by LordSimal** [comment]
Well I thought of something like an additional table called `queued_job_dependencies` which only contains 

- parent_id
- child_id

With that we can make infinite Parent-Child connections between queued_jobs and check in the run command if a given job has parent jobs. If parent jobs are present and not all are processed successfully then don't run the current job (maybe throw a special exception or something)

But maybe my logic is flawed 😅

**Comment by dereuromark** [comment]
I dont think that works with the current way the query is pulling jobs from DB.
This would need to be a pre-query to fetch "blocked items" and then do the actual query, adding some load onto the whole thing.

Maybe a different workaround can be a delay set +x hours, and then reset once the job ran.
But then this would be hacked into the user land code.

For any other such things I usually just spawn the depending jobs at the end of the actual job, triggering the follow ups right when they are supposed to be able to run.
For me this is the cleanest approach given the current way it works in this simple queue system.

**Comment by LordSimal** [comment]
well, that convinced me 😄

I was just thinking of a way how to implement a preplaned, customizable milestone system where I can set dependencies of future milestones (here jobs) and add the ability to de-/activate planned jobs.
But I guess this is out of the scope of this plugin 😄
