### ISSUE TITLE
Add current active job to worker processes list

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-queue#281]
If a worker is currently processing a job it would be awesome if the processes list would show the currently processed job.

With this it would be easier to debug hanging jobs/workers in a setup where multiple workers are present.

**Comment by dereuromark** [comment]
Should be possible using the joined assoc.
If u can make a PR with this addition, I am happy to merge it.

**Comment by LordSimal** [comment]
I will tackle this first, then the reusable Emails 😉
