### ISSUE TITLE
Send reusable Emails via EmailTask

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-queue#282]
Currently the EmailTask requires a MailerObject on which the `->deliver($content)` function is being called.

But what If I have a bunch of `Reusable Emails` (https://book.cakephp.org/4/en/core-libraries/email.html#creating-reusable-emails) and want to send them via the EmailTask?

I usually call something like 
```
$this->getMailer('MyMailer')->send('myEmail', [$var1, $var2, $var3]);
```

This is currently not possible as far as I can see it.

**Comment by dereuromark** [comment]
Do u want to make a PR here?

**Comment by dereuromark** [comment]
What about reusable emails for the case when you provide settings via array?
So no mailer object in queue DB, but only the config?

Should we here also allow this to be used as such? Or is the current way now fine?

**Comment by LordSimal** [comment]
Currently if the provided `$data['settings']` is not a Mailer object then the `action` value doesn't do anything.

But if a custom Mailer class is set via `Queue.mailerClass` config we could allow it. Don't know if we should because for me the current way is totally fine.
Only if someone would have one generic Mailer Class which is used to send a bunch of different mails it could be usefull I would guess.
