### ISSUE TITLE
Change "failed" column to "attempts"

### ISSUE THREAD

**Issue by kburton-dev** [dereuromark/cakephp-queue#299]
Change "failed" column to "attempts" and update logic accordingly (and increment this value _prior_ to job execution).

If I have a job that causes the process to run out of memory, the job is never marked as failed, and later workers will pick it up and try to execute it again regardless of the "retries" task property. This can cause the queue_processes table to fill up when there are in fact no workers running, and prevents the start up of new workers.

There are a few ways around this but I feel like the above would be a simpler way to prevent this kind of problem from happening.

@dereuromark do you have any thoughts on something like this?

**Comment by dereuromark** [comment]
So you mean you would first log "attempt + 1" before starting the job?

The memory issue is always a bit tricky with PHP and execution etc.
But yeah, that could probably be a possible workaround.

If you have ideas here, feel free to make a PR.

**Comment by kburton-dev** [comment]
While working on this, I realise that for backwards compatibility, it might make more sense to add a field "attempted," instead of renaming the "failed" column. I am unsure though because the thought of having two columns where the meaning of either, can be inferred by the other is a bit odd to me.

I think I might just bake a migration script or something to increment that column (I don't want old jobs which have were executed successfully to remain with an "attempted" value of 0).

**Comment by dereuromark** [comment]
Yeah, you can add "attempts" field and write to it, but not use it (read from it).
Then you can add a feature toggle (e.g. `Queue.useAttempts`) to activate this instead of failed for reading or inside logic.

What do you think?

If this is too complicated we can also directly plan a new major release v7. Also no big deal.
Migration would be minimal: `bin/cake migrations run -p Queue`, done.

**Comment by dereuromark** [comment]
I still like your idea. If you want to continue this, would be awesome!

**Comment by kburton-dev** [comment]
I keep going back and forward on this in my mind. Initially I made a commit changing the column name "failed" to "attempted" and then made the changes in the code.

However, when I was writing the migration to create the new column, fill it with data, and remove the failed column, I started thinking about people that might deploy this code to their production environment. If there are queue workers running while the migration script effectively renames the columns, it might issues in those workers and jobs might be executed multiple times before the worker stops.

Then I thought about just having both columns, but I don't like the idea of having a "failed" column which contains data that can be derived from the "attempted" column.

Perhaps I am going to scrap all of the above, and go with what you originally suggested, both columns while giving the user the option of toggling the feature through the config.

**Comment by dereuromark** [comment]
Yes, for BC reasons the feature flag is the best option for a minor release.
Whenever you migrate you must have no active jobs of course

Also, next major then only uses the new way.

**Comment by dereuromark** [comment]
Are you still interested to try this as PR?

**Comment by kburton-dev** [comment]
Unfortunately not @dereuromark, I'm not working with any cakephp apps at the moment.

**Comment by dereuromark** [comment]
If anyone is interested, you could PR this against the new cake5 branch for CakePHP 5.0
Here we also dont need to keep any BC, so one field can directly be dropped, and the other created.

**Comment by kburton-dev** [comment]
I'm interested in giving this another crack if no one else is. Is the cake5 branch still coming?

**Comment by dereuromark** [comment]
Yes, by tomorrow

**Comment by dereuromark** [comment]
@kburton-dev Ping

**Comment by kburton-dev** [comment]
I have prepared the branch in my fork, though I need to update some of the template logic as some of it doesn't make sense now that I increment the `attempts` prop when requesting the job.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/pull/364
