### ISSUE TITLE
Update docs for end command

### ISSUE THREAD

**Issue by mfrascati** [dereuromark/cakephp-queue#308]
It seems that v6 docs are reporting an old syntax to end workers

![image](https://user-images.githubusercontent.com/2734747/141451084-24f4c6e0-b43d-4a9d-b8f8-2cad3c580de6.png)

```
bin/cake queue end -q
Unknown command `cake queue`. Run `cake --help` to get the list of commands.
Did you mean: `queue add`?

Other valid choices:

- help
- version
- cache
- one
- parola
- i18n
- routes
- server
- queue add
- queue info
- queue run
- queue worker
- queue job
```

it should be

```
bin/cake queue worker end all
```

**Comment by dereuromark** [comment]
Can you maybe make a PR here, that would be awesome

**Comment by mfrascati** [comment]
Sure, done it https://github.com/dereuromark/cakephp-queue/pull/309
