### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by marianodonal** [dereuromark/cakephp-queue#311]
Hi Mark, i cannot get it to work.
I'm performing a bull import and the adding to job the sending of emails with credentials:

```
$mailer = $this->getMailer('User');
$data = [
'settings' => $mailer,
'action' => 'credentials',
'vars' => ['user' => $user, 'tmp_pwd' => $tmp_pwd]
];
$options = [
'reference' => $sid,
'job_group' => 'bulk-import',
'notBefore' => $entity->created->modify('+15 seconds')
];
$this->QueuedJobs->createJob('Queue.Email', $data, $options);
```
and then

```
$shell = new \Cake\Console\Shell;
$shell->dispatchShell('queue', 'run');
```

After that, i run the shell command to run the job but always get an error:

**Shell class for "Queue" could not be found. If you are trying to use a plugin shell, that was loaded via $this->addPlugin(), you may need to update bin/cake.php to match https://github.com/cakephp/app/tree/master/bin/cake.php**

If i run the shell command from terminal it performs job well but not receiving any emails.
I'm using mailhog.

Thanks

**Comment by dereuromark** [comment]
Why are you
```
$shell->dispatchShell(..)
```
?
Where is this documented?
This is completely against the idea

You run a cronjob in the background for the runner, as documented.
Then putting in the job via createJob() is all that is needed.

**Comment by marianodonal** [comment]
Thank you, now i get it.
I'm facing the same problem with emails, when the job run and complete no emails are sent.

**Comment by dereuromark** [comment]
You need to check why, but that's not an issue of the plugin.

**Comment by marianodonal** [comment]
If i use

`$this->getMailer('User')->send('credentials', [$userWithHome, $tmp_pwd]);`

it works well and emails are sent but if i use 

```
$data = [
'settings' => $mailer,
'action' => 'credentials',
'vars' => [$userWithHome, $tmp_pwd]
];
$options = [
'reference' => $sid,
'notBefore' => $last_cron
];

$this->QueuedJobs->createJob('Queue.Email', $data, $options);
```

mails are not sent.

**Comment by LordSimal** [comment]
When the runner is executing your mail job it should finally execute this line which is exactly what you want
https://github.com/dereuromark/cakephp-queue/blob/master/src/Queue/Task/EmailTask.php#L120

Maybe try to debug it via setting a breakpoint at the start of the run() function and see where it deviates

**Comment by marianodonal** [comment]
I solved it making my own task.
Thank you very much
