### ISSUE TITLE
Execute QueueProcess on the same server where the task is created

### ISSUE THREAD

**Issue by androideo** [dereuromark/cakephp-queue#312]
I am using the queue for uploading files to a certain external machine. Everything works fine so far. :)

If I am introducing auto-scaling to my system, and upload a file to server-a, a queueProcess from server-b cannot execute the task and would fail. Is there any option that queueProcess from server-a executes only tasks that have been created by server-a?

**Comment by dereuromark** [comment]
You should probably upload to a common shared space, like some cloud storage.

But as for your server topic:
https://github.com/dereuromark/cakephp-queue/tree/master/docs#multi-server-setup

You could try to add the server info into the reference of a task and see if that can be filtered then
Maybe we need to build an extension for this, as right now it can mainly only filter on task names etc.

**Comment by androideo** [comment]
I already had a look in the Processor->run() + QueuedJobs->requestJob methods and realized that it will be difficult to override this those methods without copy&paste. 
It would be nice if I can pass conditions as an options array, but still its not solved, since I can recall the server_names from the console itself :/

> You should probably upload to a common shared space, like some cloud storage.

This is probably the most stable solution.
