### ISSUE TITLE
SQL server compatibility problem (PDOException on SQL server)

### ISSUE THREAD

**Issue by bor-attila** [dereuromark/cakephp-queue#317]
We dropped all MySQL dependencies and moved to Azure SQL server.

Sadly, the plugins stopped working.

The problem is:
[PDOException] SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Line 1: FOR UPDATE clause allowed only for DECLARE CURSOR

Full stack trace with an older version was:
 [PDOException] SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Line 1: FOR UPDATE clause allowed only for DECLARE CURSOR. in /app/site/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php on line 180
Stack Trace:
- /app/site/vendor/cakephp/cakephp/src/Database/Statement/StatementDecorator.php:180
- /app/site/vendor/cakephp/cakephp/src/Database/Connection.php:337
- /app/site/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php:70
- /app/site/vendor/cakephp/cakephp/src/Database/Connection.php:340
- /app/site/vendor/cakephp/cakephp/src/Database/Query.php:250
- /app/site/vendor/cakephp/cakephp/src/ORM/Query.php:1148
- /app/site/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php:287
- /app/site/vendor/cakephp/cakephp/src/ORM/Query.php:1096
- /app/site/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php:494
- /app/site/vendor/dereuromark/cakephp-queue/src/Model/Table/QueuedJobsTable.php:535
- /app/site/vendor/cakephp/cakephp/src/Database/Connection.php:686
- /app/site/vendor/dereuromark/cakephp-queue/src/Model/Table/QueuedJobsTable.php:550
- /app/site/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php:222
- /app/site/vendor/cakephp/cakephp/src/Console/Shell.php:499
- /app/site/vendor/cakephp/cakephp/src/Console/CommandRunner.php:352
- /app/site/vendor/cakephp/cakephp/src/Console/CommandRunner.php:169
- /app/site/bin/cake.php:12

I think the problem is the:

`$job = $query->find('all', $options)
->enableAutoFields(true)
->epilog('FOR UPDATE')
->first();`

This query I think is MySQL specific : )

**Comment by dereuromark** [comment]
Are you able to make it agnostic by using DB switches maybe?
Feel free to make a PR that works for all DB types.
We should then also have a better CI here maybe.

**Comment by bor-attila** [comment]
For **SQLite** I think there is no _'nice'_ solution, bcz does not support row locking. there is some kind of locking but for the whole transaction and not for the row. In case of SQLite maybe just skip the locking part ? [^note]

For **PostgreSQL** I have no idea - my bad - I never used, but based on quick search the current solution does the job.

For **MySQL** the current solution is ok

For **SQL server** is tricky. Locking looks like this:
```
BEGIN TRANSACTION;
SELECT 
	[id], [zip] 
FROM 
	[dbo].[addresses] 
WITH 
	(UPDLOCK, ROWLOCK)
WHERE 
	[id] = 18195;
COMMIT TRANSACTION;
```
It is possible to achieve this with CakePHP's ORM ? I'm affraid it's not.
[^note]:
    Imo who needs to use locking in SQLite maybe, should avoid this dbms.

**Comment by dereuromark** [comment]
We can add if/else per type, like in other cases 
And only Start to Support what we know
