### ISSUE TITLE
RFC: EmailTask with more options

### ISSUE THREAD

**Issue by mrothauer** [dereuromark/cakephp-queue#329]
Hi,

thanks for this great plugin, I already use it in my project and it does its job very well. But now I need some extra functions for the [EmailTask](https://github.com/dereuromark/cakephp-queue/blob/master/src/Queue/Task/EmailTask.php).

* adding attachments
* add cc and bcc fields

I'm aware that there exists another [EmailQueue](https://github.com/lorenzo/cakephp-email-queue), but this plugin seems not very active (open PR since November 2021). And I prefer using only one queue plugin.

**Comment by dereuromark** [comment]
You can pr whatever is missing
Also Note that most of those things exist as array input already afaik

**Comment by mrothauer** [comment]
where exactly would I find "those things"?

I only found these options (no attachments, no cc and no bcc):
https://github.com/dereuromark/cakephp-queue/blob/8a4d71ec883be5e361191cd417fc9779738fdcf1/src/Queue/Task/EmailTask.php#L87-L92

**Comment by mrothauer** [comment]
ok thank you,  I'll give it a try, it might last a few days though...

**Comment by mrothauer** [comment]
Finally I found everything I need - it works great!

One last question: I use the EmailTask to send emails with attachments that are often bigger than 64KB (the default size of MySQL-type "text" (Table: queue_jobs, field: data).

I changed the type to "mediumtext", 16MB should be enough.

Isn't that a common use case and 64KB are relatively small? Can I prepare a migration PR?
