### ISSUE TITLE
Lock wait timeout exceeded

### ISSUE THREAD

**Issue by ishu-oct** [dereuromark/cakephp-queue#330]
I am using cakephp-queue to send mails to users.  I am getting this lock wait timeout error when I try to send mails.  

```
Exception: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
In [/var/www/html/my-test-server/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php, line 39]

Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 185
file_put_contents - [internal], line ??
Cake\Log\Engine\FileLog::log() - CORE/src/Log/Engine/FileLog.php, line 140
Cake\Log\Log::write() - CORE/src/Log/Log.php, line 392
Cake\Log\Log::error() - CORE/src/Log/Log.php, line 461
Cake\Error\ErrorLogger::log() - CORE/src/Error/ErrorLogger.php, line 91
Cake\Error\BaseErrorHandler::logException() - CORE/src/Error/BaseErrorHandler.php, line 334
Cake\Error\ConsoleErrorHandler::handleException() - CORE/src/Error/ConsoleErrorHandler.php, line 65
[main] - [internal], line ??

2022-05-23 18:20:54 error: [PDOException] SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction in /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php on line 39
Stack Trace:
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php:39
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Database/Connection.php:337
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php:70
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Database/Connection.php:340
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Database/Query.php:250
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/ORM/Query.php:1148
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php:287
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/ORM/Query.php:1096
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Datasource/QueryTrait.php:494
- /var/www/html/my-test-server/vendor/dereuromark/cakephp-queue/src/Model/Table/QueuedJobsTable.php:620
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Database/Connection.php:686
- /var/www/html/my-test-server/vendor/dereuromark/cakephp-queue/src/Model/Table/QueuedJobsTable.php:635
- /var/www/html/my-test-server/vendor/dereuromark/cakephp-queue/src/Queue/Processor.php:139
- /var/www/html/my-test-server/vendor/dereuromark/cakephp-queue/src/Command/RunCommand.php:96
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Console/BaseCommand.php:179
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Console/CommandRunner.php:334
- /var/www/html/my-test-server/vendor/cakephp/cakephp/src/Console/CommandRunner.php:172
- /var/www/html/my-test-server/bin/cake.php:12
```

@dereuromark Can you please let me know how to fix this issue and also let me know if I have to add anything further?

**Comment by LordSimal** [comment]
To not get into too much detail but this error is not caused by the SQL generated by the plugin but rather (or most likely) by your app and/or other software overloading your database server.
InnoDB locks the table whenever someone is doing stuff with it so data keeps consistent. But if that statement just takes too long (and there are many many reasons why this can happen) then the table is still locked and therefore no one else (in your example the Queue Plugin) can't access the table.
Try googleing that error and you will find loads of stuff.

**Comment by ishu-oct** [comment]
Hi @LordSimal ,yes! but earlier I was using the lower version of this cakephp-queue plugin and the app code was working as expected and recently, I have upgraded it to the latest version of this plugin and I am facing such issue and also the app code is still the same. Could you let me know your ideas on this?

**Comment by LordSimal** [comment]
can you clarify which 2 version you are using exactly. So what exactly is the "lower version" and what is the "current version" for you right now.

**Comment by ishu-oct** [comment]
Yes, @LordSimal , The lower version is 3.7.1 and the current version is 6.3.1.  If I run `bin/cake queue run` from the terminal, it seems like that I am not facing any issue but when I run that from the code i.e. something like this,

`public function runWorker()
 {
     $cmd = ROOT . DS . 'bin' . DS . 'cake queue run';
     exec($cmd);
 }`
 I am facing the lock wait time out issue.

**Comment by ishu-oct** [comment]
Thanks.  This issue got resolved.  The application code has already started a transaction and it is trying to insert records in queued_jobs table using createJob and when we run the queue, transaction is again opened in requestJob method.
Since the previous transaction is not committed, the query in the requestJob has to wait and it got lock wait timeout issue.  
Once after trying to make the queue run command to act as a background process, it got resolved.
