### ISSUE TITLE
Parallel Queue for different Jobs

### ISSUE THREAD

**Issue by ashishkshah48** [dereuromark/cakephp-queue#336]
Hi,

I am using the cakephp3.8 version with your queue plugin. I have added so many things to run into the background which includes so many DB queries and AWS S3 object cloning. My site is hosted on AWS EC2 t2.meduim with ELB.

But as so many queue job is there they slow down another queue job which is in priority.

so my question is can I created two different queues which handled separate job types and are not interlinked with each other?

Also, how can I run multiple processes for a queue to run faster on AWS EC2 with ELB?

Please reply

**Comment by dereuromark** [comment]
I dont think this plugin is supposed to handle high traffic queues
If you need that, you might want to look into more professional tools here maybe.

**Comment by ashishkshah48** [comment]
If you have any idea about that kinds of tools then let me know.

Do you think AWS SQS will helo me in this case?

**Comment by dereuromark** [comment]
See https://github.com/FriendsOfCake/awesome-cakephp#queue
