### ISSUE TITLE
Deprecation message in PHP 8.1

### ISSUE THREAD

**Issue by mrothauer** [dereuromark/cakephp-queue#340]
in version 6.4.2

```
deprecated: 16384 :: allowEmpty() is deprecated. Use allowEmptyString(), allowEmptyArray(), allowEmptyFile(), allowEmptyDate(), allowEmptyTime(), allowEmptyDateTime() or allowEmptyFor() instead.
D:\htdocs\foodcoopshop.dev\vendor\dereuromark\cakephp-queue\src\Model\Table\QueuedJobsTable.php, line: 178
```

The field progress has `float` as type, I don't know if allowEmptyString is the correct validation method.

**Comment by dereuromark** [comment]
:/ I hate those new methods
I wonder what the best way forward would be. 
For now I would recommend silencing vendor and specifically that plugin for the deprecations as documented.

**Comment by mrothauer** [comment]
ok thanks for your quick reply
https://github.com/foodcoopshop/foodcoopshop/commit/124cc0746237483fa4b11eb153b6dff6cfb8da5b

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/releases/tag/6.4.3
