### ISSUE TITLE
Regression: Deprecation Warning related to TimeHelper

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-queue#346]
https://github.com/dereuromark/cakephp-queue/commit/3c18f31dd3cea930ed1ee37068375fea2944dcef
This change now causes the following deprecation warning in the latest 6.5.0 update on e.g. the index page of the QueuedJobsController:
```
CAKE/I18n/Time.php:134
The `Time` class has been deprecated. Use the immutable alternative `FrozenTime` instead /Users/kevinpfeifer/Documents/Sunlime/alfred/vendor/cakephp/cakephp/src/I18n/Time.php, line: 134 You can disable all deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED`. Adding `vendor/cakephp/cakephp/src/I18n/Time.php` to `Error.ignoredDeprecationPaths` in your `config/app.php` config will mute deprecations from that file only.
```

**Comment by dereuromark** [comment]
The main issue was a conflict with a similar helper defined on project level
Do you have an idea how this can be solved?

**Comment by LordSimal** [comment]
I would say change 
```
protected $_defaultConfig = [
	'engine' => 'Tools\Utility\Time', // Deprecated, use Tools\Utility\FrozenTime instead
];
```
to
```
protected $_defaultConfig = [
	'engine' => 'Tools\Utility\FrozenTime',
];
```
inside the `src/View/Helper/TimeHelper.php` since those 2 classes have basically the same functionality but the current default one is just using the old, deprecated Time class

**Comment by dereuromark** [comment]
Sounds good
Do u want to make a PR?
