### ISSUE TITLE
JsonSerializer breaks EmailTask

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-queue#354]
The recently added serializer config to change `(un)serialize` to `json_(de-en)code` now results in the fact, that the job type `Queue.Email` doesn't work anymore with Mailer objects

```
$this->QueuedJobs->createJob('Queue.Email', [
    'settings' => $this->getMailer('Sunlime'),
    'action' => 'notifyPM',
    'vars' => [$projectDataEntry],
]);
```

because (of course) `json_encode()` doesn't persist objects.

The same will happen if settings is a `\Cake\Mailer\Message` object.

## Possible fix

In my opinion something like this would be better
```
$this->QueuedJobs->createJob('Queue.Email', [
    'settings' => 'mailer',
    'mailer' => 'Sunlime'
    'action' => 'notifyPM',
    'vars' => [$projectDataEntry],
]);
```
and then we fetch the mailer object in the `EmailTask`

This would fix the `EmailTask` for mailer instances but I have no idea how one would make a message object re-buildable from pure json data.

**Comment by dereuromark** [comment]
But did u change the config to json? As by default nothing should change

**Comment by LordSimal** [comment]
Yes sorry, I did change to 
```
'serializerClass' => \Queue\Utility\JsonSerializer::class,
```
with the current state of master ^^

**Comment by dereuromark** [comment]
Can you make a PR here? We need to be careful to be as bc as possible for legacy serialize

**Comment by LordSimal** [comment]
Sure, I can try to get that working with the current Email task.

But in the long run I think it would be better if users stop persisting serialized objects and therefore those plugin provided tasks need to be adjusted. But this is of course up to you for future major versions.

**Comment by dereuromark** [comment]
We can also create a new email task and deprecate old one

**Comment by LordSimal** [comment]
Well to be honest I am not sure which kind of mail sending methodology is the most common.

I personally always create a Mailer class to have re-usable emails easily accessible.
