### ISSUE TITLE
Error: Queue.ConfigureHelper could not be found.

### ISSUE THREAD

**Issue by passchn** [dereuromark/cakephp-queue#357]
When trying to view a Queued Job, the error `Error: Queue.ConfigureHelper could not be found.` is thrown due to a call to `$this->Configure->read('debug')`.

I could not find a ConfigureHelper in either the Queue or the Tools plugin. I guess it should be a check like `Configure::read(debug)`. 

How is one supposed to access the template? Should the current configure always be set as a property of `AppView`? 

https://github.com/dereuromark/cakephp-queue/blob/847e7ed7707562029fa5593880286f6bd1b1e6b4/src/Template/Admin/QueuedJobs/view.ctp#L126

**Comment by dereuromark** [comment]
The controller action should have
https://github.com/dereuromark/cakephp-queue/blob/cake3/src/Controller/Admin/QueueController.php#L139

If not, you can either PR that, as it would be available like in all other actions etc.

**Comment by passchn** [comment]
I just saw that the Helper has already been set: 
https://github.com/dereuromark/cakephp-queue/compare/4.3.1...cake3 

Would you mind publishing a v4.3.2 with the changes? They are from 2020 and 20201 :D

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/compare/4.4.0...4.4.1

**Comment by passchn** [comment]
Sorry, I was blind obviously..
