### ISSUE TITLE
Wrong path with compser

### ISSUE THREAD

**Issue by Dee-Fuse** [dereuromark/cakephp-queue#37]
When installing cakephp-queue for CakePHP 3.X with composer, the path for this Plugin in "vendor/cakephp-plugins.php" looks like:
`'Queue' => $baseDir . '/vendor/dereuromark/cakephp-queue/'`
but should be:
`'Queue' => $baseDir . '/vendor/dereuromark/Queue/'`
this results in:
`Exception: Could not load configuration file: .../vendor/dereuromark/cakephp-queue/config\queue.php in [...\vendor\cakephp\cakephp\src\Core\Configure\FileConfigTrait.php, line 59]`

**Comment by dereuromark** [comment]
I think we should drop the plugin installer name part? https://github.com/dereuromark/cakephp-queue/blob/master/composer.json#L25

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/commit/b107c96f01e47bf89315db88ba26bd0d3a5ad188
