### ISSUE TITLE
How to test with `ServicesTrait`

### ISSUE THREAD

**Issue by challgren** [dereuromark/cakephp-queue#370]
So I having a bit of an issue testing a Task that uses ServicesTrait with an undefined function get() on null. Would you be able to share some example code to test a task with DI

An example test I am writing is

```
Configure::write('WyriHaximus.FlyPie.s3_scan_images', [
    'adapter' => InMemoryFilesystemAdapter::class,
    'vars' => [],
]);
$this->mockService(UnleashService::class, function() {
    return new UnleashService();
});
$this->BatchEmailTask = new LabelBatchEmailTask();
$data = [
    'device_id' => $device->id,
    'batch_id' => $batch_id,
    'batch_name' => 'My Batch',
];
$this->BatchEmailTask->run($data, 1);
```

My task does use `Queue\Queue\ServicesTrait`

**Comment by dereuromark** [comment]
@LordSimal did u so such a test?

**Comment by LordSimal** [comment]
The container instance only gets set if a task is being processed by the Processor.
https://github.com/dereuromark/cakephp-queue/blob/master/src/Queue/Processor.php#L200-L215

Therefore manually calling `run()` on a Task object won't automatically inject DI dependencies.

The tests I provided when I added the DI feature to this plugin used the `$this->exec()` method of the ConsoleIntegrationTestTrait. See https://github.com/dereuromark/cakephp-queue/blob/master/tests/TestCase/Command/RunCommandTest.php#L59

**Comment by dereuromark** [comment]
I wonder if we need some more docs on this
