### ISSUE TITLE
Organize task in sub folders

### ISSUE THREAD

**Issue by rudy1976s** [dereuromark/cakephp-queue#371]
Hello Mark
I have tried to organize task under subfolders , making corrections to namespaces.
It seems not working as soon as namespace of the task changes: is it possible to group tasks under sub folders?

Thank you
Rudy

**Comment by dereuromark** [comment]
I like the idea, so yeah please do :)

**Comment by dereuromark** [comment]
Please check https://github.com/dereuromark/cakephp-queue/pull/376

Let me know if it works fully, and maybe someone can help to finish up the remaining parts as PRs to that one.
