### ISSUE TITLE
Loading of configuration not working

### ISSUE THREAD

**Issue by Txxkirsch** [dereuromark/cakephp-queue#372]
Hello Mark,

you are stating in your docs: https://github.com/dereuromark/cakephp-queue/blob/master/docs/sections/configuration.md
that the default-configuration will be loaded when you set `['bootstrap'=>true]` while loading the plugin in Application.php.

This doesn't work because the Plugin.php has no bootstrap-method.

Greetings!

**Comment by dereuromark** [comment]
It does only need one if no file can be found right?

**Comment by Txxkirsch** [comment]
In my opinion it should always have bootstrap-method which loads the default configuration or the documentation shouldn't state that ['bootstrap'=>true] loads the default config.

**Comment by dereuromark** [comment]
Do you want to make a PR?
