### ISSUE TITLE
Disabling log nothing to do sleeping

### ISSUE THREAD

**Issue by rudy1976s** [dereuromark/cakephp-queue#375]
Hello Mark!
is there a way to disable the log when there is nothing to do ?
in large environment (when queues run often) there will be a large amount of logs  in syslog.
Thank you in advance

Rudy

**Comment by dereuromark** [comment]
Are u not using -q in prod?
Or what kind of log info is it?

**Comment by dereuromark** [comment]
See docs about "Setting up the trigger cronjob"
