### ISSUE TITLE
terminateProcess() didn't like the default parameter of SIGTERM php 7.4

### ISSUE THREAD

**Issue by umer936** [dereuromark/cakephp-queue#377]
terminateProcess() is calling the default parameter of SIGTERM as the string 'SIGTERM' instead of 15. 
Seemed like it wasn't using the PHP internal constant for pcntl https://www.php.net/manual/de/pcntl.constants.php#115603

I overwrote it to be 9 for my case in the vendor. 

When I get a chance, I'll test this out more but I wanted to put this issue in before I forget.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/commit/9670cfa624c954e3565da6353910df9e85ab9265
