### ISSUE TITLE
Job is not getting picked up

### ISSUE THREAD

**Issue by harshavardhan-gopalakrishnan** [dereuromark/cakephp-queue#385]
There are jobs to be fetched in the queued_jobs but processes in queue_processes are idle and are not picking up the jobs. The max worker count in 3 and I have 3 records in queue_processes table and none of it is picking the jobs.  Below is the configuration.
'Queue' => [
        'defaultworkertimeout' => 172800,
        'workermaxruntime' => 0,
        'exitwhennothingtodo' => true,
        'cleanuptimeout' => 172800,
        'pidfilepath' => false,
        'maxworkers' => 3,
        'log' => true,
        'defaultworkerretries' => 0
    ]
Despite setting exitwhennothingtodo to true, there are instances where the processes are not being deleted as expected.

Additionally, I've encountered deadlock issues where two processes are attempting to pick up the same job simultaneously.

I'm seeking assistance to resolve this situation and optimize the configuration to ensure that jobs are consistently picked up by idle processes and to prevent deadlock scenarios. Your insights and guidance would be greatly appreciated.

**Comment by LordSimal** [comment]
I am running 5 processes in parallel which have a TTL of 1 minute and I haven't run into this problem yet.
I'd recommend you enable the query log of your datasource and look at the SQL queries which are being executed to fetch for new jobs.
Then look at what is amiss in that query and/or your data in your table.

**Comment by dereuromark** [comment]
'defaultworkertimeout' => 172800,
'workermaxruntime' => 0,

That looks like a dangerous setting, I would never give it 0 (never stopping), better to be close to a minute, and spawn new ones every minute.

**Comment by harshavardhan-gopalakrishnan** [comment]
In our production environment, we're encountering a problem where certain jobs aren't being processed, and we've noticed that there are idle processes listed in the 'queue_processes' table. Unlike in our local development environment, where we haven't been able to replicate this issue (i.e., jobs are consistently being picked up ).

What would be the most effective approach to address this problem?

**Comment by dereuromark** [comment]
Sounds like they are not shutting down normally. Maybe they got interrupted badly?
Make sure the settings are as listed above, with only a few min normal runtime, and workertimouts in reasonable length
Then this should also auto clean itself.
