### ISSUE TITLE
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'priority' in 'order clause'

### ISSUE THREAD

**Issue by ConvivialSoftware** [dereuromark/cakephp-queue#393]
Hi
i am using old cakephp 2.10
I installed (https://github.com/dereuromark/cakephp-queue/tree/cake2) package as instructed in document.
To add table i ran cake Schema create -p Queue

now i added job in table but when i run cake Queue.Queue runworker it gives 
Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'priority' in 'order clause'
#0 /home/demosite/public_html/cakephp2/lib/Cake/Model/Datasource/DboSource.php(489): PDOStatement->execute(Array)
#1 /home/demosite/public_html/cakephp2/lib/Cake/Model/Datasource/DboSource.php(455): DboSource->_execute('SELECT `QueuedT...', Array)
#2 /home/demosite/public_html/cakephp2/lib/Cake/Model/Datasource/DboSource.php(702): DboSource->execute('SELECT `QueuedT...', Array, Array)
#3 /home/demosite/public_html/cakephp2/lib/Cake/Model/Datasource/DboSource.php(1213): DboSource->fetchAll('SELECT `QueuedT...', Array)
#4 /home/demosite/public_html/cakephp2/lib/Cake/Model/Model.php(3040): DboSource->read(Object(QueuedTask), Array)
#5 /home/demosite/public_html/cakephp2/lib/Cake/Model/Model.php(3012): Model->_readDataSource('all', Array)
#6 /home/demosite/public_html/cakephp2/app/Plugin/Queue/Model/QueuedTask.php(173): Model->find('all', Array)
#7 /home/demosite/public_html/cakephp2/app/Plugin/Queue/Console/Command/QueueShell.php(205): QueuedTask->requestJob(Array, NULL)
#8 /home/demosite/public_html/cakephp2/lib/Cake/Console/Shell.php(459): QueueShell->runworker()
#9 /home/demosite/public_html/cakephp2/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand('runworker', Array)
#10 /home/demosite/public_html/cakephp2/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#11 /home/demosite/public_html/cakephp2/app/Console/cake.php(47): ShellDispatcher::run(Array)
#12 {main}

Do i need to run migration? as i am using old plugin and created tables as instructed.

_Originally posted by @ConvivialSoftware in https://github.com/dereuromark/cakephp-queue/issues/214#issuecomment-1848259298_

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/wiki
V2 is dead and eol
You need to provide PRs to merge, or fork and use your own repo.
