### ISSUE TITLE
Change to JsonSerializer by default in next minor or major

### ISSUE THREAD

**Issue by LordSimal** [dereuromark/cakephp-queue#394]
I was just checking my queue config and was kind of surprised that the Cake5 version of this plugin hasn't changed to use the JsonSerializer by default for its `serializerClass` config.

I know this is because of BC concerns but as it is said in the docs itself it is recommended to switch to the JsonSerializer in the long run.

**Comment by dereuromark** [comment]
Oversight when releasing v5

**Comment by LordSimal** [comment]
I would welcome using the ORM's native JsonType for that.

Just depends on how you want to handle this from an upgrade path perspective since this is not BC. Would you make this configurable in a new config key? Or would you expect users to overwrite the QueuedJobsTable?

**Comment by dereuromark** [comment]
We can major and provide some upgrade doc?

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/issues/398 will take care of this in a probably new major
