### ISSUE TITLE
Composer installation for CakePHP 3 inaccuracy

### ISSUE THREAD

**Issue by drmonkeyninja** [dereuromark/cakephp-queue#40]
You've stated in your readme file that you can install with composer using `require dereuromark/cakephp-queue:3.0` for CakePHP 3 but don't appear to have tagged the repository with this version number yet.

**Comment by dereuromark** [comment]
Closed with https://github.com/dereuromark/cakephp-queue/commit/831b0c0ba5597d70ab06c11ae8659f83eea1ad28 for now

**Comment by drmonkeyninja** [comment]
:+1:
