### ISSUE TITLE
Filling status field

### ISSUE THREAD

**Issue by rudy1976s** [dereuromark/cakephp-queue#402]
Hi Mark

in your following function, found in **QueuedJobsTable**

```
public function markJobDone(QueuedJob $job): bool {
		$fields = [
			'progress' => 1,
			'completed' => $this->getDateTime(),
		];
		$job = $this->patchEntity($job, $fields);

		return (bool)$this->save($job);
	}
```

is there a particulare reason why the status fields is not filled with status = 1 or something like that?
It seems that status field is never updated.

Thank you in advance

Rudy

**Comment by dereuromark** [comment]
That is a free text field
```php
$table->changeColumn('status', 'string', [
	'length' => 255,
	'null' => true,
	'default' => null,
]);
```
And can be field with custom input

It is indeed dormant otherwise and unused by the plugin code itself.
The docs could be a bit more clear about this.

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/pull/189
