### ISSUE TITLE
Documentation not updated to CakePHP5

### ISSUE THREAD

**Issue by utdrmac** [dereuromark/cakephp-queue#403]
Trying to use this plugin by following the documentation. I first did the [basic setup](https://github.com/dereuromark/cakephp-queue/blob/master/docs/sections/basic_setup.md), I added the addPlugin() in my src/Application.php::bootstrap(), I added my config to `config/app_local.php`, I ran the migration to create the db tables, and now I'm trying to [create a job](https://github.com/dereuromark/cakephp-queue/blob/master/docs/sections/queueing_jobs.md).

In my controller,
```
class PreviewController extends AppController
{
...
        public function export(string $project_id): \Cake\Http\Response
	{
		$this->loadModel('Queue.QueuedJobs');

		// Create the task
		$jobId = $this->QueuedJobs->createJob(ExportNotionDocTask::class, ['project_id' => $project_id]);
        }
}
```

`Call to undefined method App\Controller\PreviewController::loadModel()`

What now? `loadModel()` only exists in CakePHP4. Can you please update the documentation for CakePHP5?

**Comment by utdrmac** [comment]
Reading your example code for the sandbox, I found references to a ModelAwareTrait. Searching Cake docs, I discovered the usage. I am now doing this:

```
use Cake\Datasource\ModelAwareTrait;
use App\Queue\Task\ExportNotionDocTask;

class PreviewController extends AppController
{
        use ModelAwareTrait; // For loading the Queue model
...
        public function export(string $project_id): \Cake\Http\Response
	{
		// Load the ORM model of the queue
		$queue = $this->fetchModel('Queue.QueuedJobs');

		// Create the task
		$jobId = $queue->createJob(ExportNotionDocTask::class, ['project_id' => $project_id]);
        }
}
```

And this seems to work. I can at least see new records being added to the database table. It would be nice to see the documentation updated with more explanation for CakePHP5 usage.

**Comment by utdrmac** [comment]
Also, the docs give this example in your controller:

`use Queue\Queue\Task\EmailTask;`

Assuming you created your task at src/Queue/Task/MyCoolTask.php, using the `bake queue_task MyCoolTask` command, the above is incorrect. You have to use `use App\Queue\Task\MyCoolTask`

**Comment by dereuromark** [comment]
Feel free to make a PR ti improve docs

**Comment by dereuromark** [comment]
I fixed what I found:
https://github.com/dereuromark/cakephp-queue/commit/29cf191fcf97ded7abe6fe9941d375964dc37dad

If there is anything else left, please click edit on the page (top right) and modify + PR the changes.
Thank you.
