### ISSUE TITLE
How can I run a task every 10s?

### ISSUE THREAD

**Issue by utdrmac** [dereuromark/cakephp-queue#423]
Big fan of this queue plugin! We are now in a situation where we'd like a task to run every time the queue wakes up (we use the default 10s sleep time). I saw your companion crontab plugin, but that seems to be limited to once-per-minute (which might actually be fine for us in the long run).

If we wanted something more frequent, what's the best plan? I had two ideas: 1) the task's run() function simply adds a new task before exiting, thereby duplicating itself, or 2) the task returns failure condition, even when it is successful, which should trigger auto-retry (but I think this might require modifying config defaultworkerretries, which would affect other jobs)

**Comment by dereuromark** [comment]
Yes, you can respan right aftewards to create more overhead, but effectively having 1s time slots.

The Scheduler plugin could theoretically also be adjusted to it
https://github.com/dereuromark/cakephp-queue-scheduler/issues/2
But someone would need to implement it
If you do, I can merge/release, or help with the finishing touch at least.

**Comment by utdrmac** [comment]
Well, I 'solved' this by having my task simply create a new task as itself, using notBefore to ensure it does not run again immediately. This has been working well for the past week.

```php
// Now plus 1hr
$nextRun = new \DateTime();
$nextRun->add(new \DateInterval('PT1H'));

$this->QueuedJobs->createJob(self::class, [], [
  'notBefore' => $nextRun->format(DATE_RFC3339)
]);
```

**Comment by dereuromark** [comment]
PT1H? why 1h
I thought this was about seconds?

**Comment by utdrmac** [comment]
Requirements changed. Having it run every 10s was ridiculous. I guess I could use the other plugin at this rate, but that seemed to require another system-php service to run every minute in order to generate the queue tasks. Doing it this way removes that extra complexity.

**Comment by dereuromark** [comment]
All right. Maybe someone else explores the < 1min topic on scheduler.
