### ISSUE TITLE
templates/Admin/QueuedJobs/view.php still references Utility\Serializer

### ISSUE THREAD

**Issue by utdrmac** [dereuromark/cakephp-queue#426]
https://github.com/dereuromark/cakephp-queue/blob/4837cdbed839d862e1fb20e095ca22e83cdbd7ef/templates/Admin/QueuedJobs/view.php#L8

**Comment by dereuromark** [comment]
https://github.com/dereuromark/cakephp-queue/commit/fcfa285c4df579ebe44f4f3bfbd50f1f907f9b78
