### ISSUE TITLE
Is there anyway to get the db schema without running migrations?

### ISSUE THREAD

**Issue by resting** [dereuromark/cakephp-queue#428]
Would prefer to just run the sql without migrations.

Is there any where we can get the schema to import directly via SQL?

Trying to run v4.4.1

**Comment by dereuromark** [comment]
Why that?

**Comment by resting** [comment]
Cause its a legacy application and didn't have migrations and I want to keep the changes to a minimum.

**Comment by dereuromark** [comment]
You can run it on a different db and then copy and paste the schema
