### ISSUE TITLE
Problem in integrating the plugin in my code

### ISSUE THREAD

**Issue by raunakbinani** [dereuromark/cakephp-queue#45]
Sir, I am being asked to define Config.systemEmail or Config.adminEmail in Configure and did this:-
        
                           Configure::write('admin', array('Email' => 'jayc@quetzal.in'));
	                   Configure::write('system', array('Email' => 'jayc@quetzal.in'));

But, sir I am still getting the same error. Sir can you please tell me what is my mistake.

**Comment by dereuromark** [comment]
Did you check the code or the test cases?
They clearly state how its done ( https://github.com/dereuromark/cakephp-tools/blob/master/tests/TestCase/Network/Email/EmailTest.php#L173 )
So in short:

    Configure::write('Config.adminEmail', 'your@email');

etc

**Comment by Oxicode** [comment]
Lol

**Comment by dereuromark** [comment]
?
