### ISSUE TITLE
Shell is not working with cake 2.x

### ISSUE THREAD

**Issue by dhananjayve** [dereuromark/cakephp-queue#47]
I am using cakephp 2.4. here is my command and its output
command:
H:\xampp\htdocs\demobackup\app\Console>cake Queue.Queue
 output:
Error: Plugin Queue could not be found.
#0 H:\xampp\htdocs\demobackup\lib\Cake\Core\App.php(367):
 CakePlugin::path('Queue')
#1 H:\xampp\htdocs\demobackup\lib\Cake\Core\App.php(228):
 App::pluginPath('Queue')
#2 H:\xampp\htdocs\demobackup\lib\Cake\Core\App.php(549):
 App::path('Console/Command', 'Queue')
#3 [internal function]: App::load('QueueShell')
#4 [internal function]: spl_autoload_call('QueueShell')
#5 H:\xampp\htdocs\demobackup\lib\Cake\Console\ShellDispa
tcher.php(250): class_exists('QueueShell')
#6 H:\xampp\htdocs\demobackup\lib\Cake\Console\ShellDispa
tcher.php(200): ShellDispatcher->_getShell('Queue.Queue')
#7 H:\xampp\htdocs\demobackup\lib\Cake\Console\ShellDispa
tcher.php(68): ShellDispatcher->dispatch()
#8 H:\xampp\htdocs\demobackup\app\Console\cake.php(37): S
hellDispatcher::run(Array)
#9 {main}
I have added in bootstrap.php
CakePlugin::loadAll();

all other plugins are working fine. Please help

**Comment by dereuromark** [comment]
I am pretty sure that's a mistake on your end. Maybe the cache needs clearing or composer is not doing what it is supposed to do.

**Comment by dhananjayve** [comment]
i had install too many times but not working.

**Comment by fordhamae** [comment]
I had this problem while trying to add a task from the CLI. It turned out I needed to be parent directory to /app. 

For example, my path is: /var/www/html/app

/var/www> cake Queue.Queue add Example  (results in the error shown here)

/var/www/html> cake Queue.Queue add Example  (works as expected)

Hope that helps anyone having this issue.

**Comment by dereuromark** [comment]
You always need - as documented - call cake from your app dir.
So navigate into your app dir and then call

    Console/cake

**Comment by fordhamae** [comment]
Noted. I realize this is not a bug. However, the cake error message and stack trace are not very helpful either. I thought explicitly explaining the problem and resolution here may be helpful to others that find this page via a google search.

**Comment by deepika1308** [comment]
Hello, 
sir i have the same problem in cakephp 2.4 but does understand how to solve this. When i tpye "Console/cake Queue.Queue "  in cake console and my home directory is 
cake>app>Console/cake Queue.Queue 
Error: Shell class QueueShell could not be found.
#0 /var/www/html/cake1/lib/Cake/Console/ShellDispatcher.php(203): ShellDispatcher->_getShell('Queue.Queue')
#1 /var/www/html/cake1/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#2 /var/www/html/cake1/app/Console/cake.php(47): ShellDispatcher::run(Array)
#3 {main}
Please Help Me..

**Comment by dhananjayve** [comment]
Check your plugin directory. It should be app/Plugin/Queue
Then run
Your path app>Console/cake Queue.Queue

**Comment by deepika1308** [comment]
Sir, 
i have check the plugin location it is correct. it is placed in app>Plugin>Queue
then if i run this command i got the same result
Error: Shell class QueueShell could not be found.
#0 /var/www/html/cake1/lib/Cake/Console/ShellDispatcher.php(203): ShellDispatcher->_getShell('Queue.Queue')
#1 /var/www/html/cake1/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#2 /var/www/html/cake1/app/Console/cake.php(47): ShellDispatcher::run(Array)
#3 {main}

**Comment by dereuromark** [comment]
Sure you loaded the Plugin?

**Comment by deepika1308** [comment]
yes sir, i have loaded the plugin. i have write this code in bootstrap.php
CakePlugin::load(array( # or CakePlugin::loadAll(array(
    'CakeResque' => array('bootstrap' => true)
));

On Tue, Jul 12, 2016 at 12:58 PM, Mark Sch. <notifications@github.com>
wrote:

> Sure you loaded the Plugin?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/dereuromark/cakephp-queue/issues/47#issuecomment-231959807>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATcntW-LrPtgWBQq9TMvoKz5JzMvXJ87ks5qU0IpgaJpZM4FUSLa>
> .
>



-- 
--
Thanks and Regards
Deepika Saini
Software Engineer - Webner Solutions Pvt. Ltd.
Web - www.webnersolutions.com
Mobile: +91-9465872987

**Comment by dhananjayve** [comment]
It seems your bootstrap setup is not correct. Use
CakePlugin::loadAll();
Or
CakePlugin::load(array('Queue' => array('bootstrap' => true)));
On Jul 12, 2016 10:55 AM, "dhananjay Verma" <dhananjayve@gmail.com> wrote:

Check your plugin directory. It should be app/Plugin/Queue
Then run
Your path app>Console/cake Queue.Queue

**Comment by bhavnasindhwani11** [comment]
has this issue been solved?
