### ISSUE TITLE
worker running more than its life set in config file 

### ISSUE THREAD

**Issue by sandeepkundu4344** [dereuromark/cakephp-queue#58]
I set worker life workermaxruntime = 6000 and set a crontab to run a worker after 10 minutes  but after 5 hours i have a 10 workers active. what is this ??

Please let me know why this is happening and is it a bug

**Comment by dereuromark** [comment]
What is your expectation?

And why would you do that? 6000 = 1.6 hours.
That is way too many works when you start one every 10 min.

Either way, you should not run more than 1-2 at the same time on a small system.

**Comment by sandeepkundu4344** [comment]
ooops sorry it was a mistake. just my bad :-)
