### ISSUE TITLE
Broken "Reset Queue Tasks" button

### ISSUE THREAD

**Issue by afkesix** [dereuromark/cakephp-queue#63]
Hi Mark,

I'm using the 2.x version of your plugin. The "Reset Queue Tasks" button on "queue/queue/admin_index" page posts to the "reset" action, however the action is named "admin_reset". So the button is not working. Is this a bug? or how can I fix it.

Thanks

**Comment by dereuromark** [comment]
No, you probably forgot to activate admin as prefix.
Then it would be `admin/queue/queue/index` as expected.
