### ISSUE TITLE
Read config values using Cake\Core\Configure

### ISSUE THREAD

**Issue by half2me** [dereuromark/cakephp-queue#66]
Instead of setting config values in app_queue.php in the config variable could we instead set config values using the conventional Cake\Core\Configure class, and do:
`Configure::write();` in the boostrap.php?

**Comment by dereuromark** [comment]
For 3.x? Yes, I would think so.
Thats what https://github.com/dereuromark/cakephp-queue/blob/master/config/bootstrap.php does afaik.

**Comment by half2me** [comment]
So I can just do this in my boostrap.php file?
``` php
Plugin::load('Queue');
Configure::write('Queue', [
    'workermaxruntime' => 60,
    'sleeptime' => 15,
]);
`

**Comment by dereuromark** [comment]
Did you try it?

**Comment by half2me** [comment]
I just started using this now, and was reading through the documentation, so no. But it seemed a bit strange for me that the recommended way to set the config values was through a separate php file instead of the usual Configure::write method that most other plugins use.

**Comment by dereuromark** [comment]
It is basically from 2.x times.
But therefore the additional docs, and maybe someone can make a PR to make the defaults the way you expect them to be.

**Comment by half2me** [comment]
Well I was just thinking it might be worth mentioning in the documentation. Should I make a PR?

**Comment by dereuromark** [comment]
Better make a PR once you confirmed everything is working and when you replace https://github.com/dereuromark/cakephp-queue/blob/master/config/bootstrap.php#L6 with some other way to ensure the defaults are all in place.

**Comment by dereuromark** [comment]
I need some help to confirm that the plugin version for 3.x is now stable enough to do a 3.0.0 release.

**Comment by half2me** [comment]
Well, I'll be happy to test it, since I'll be needing it in my project which is using Cake 3.2

**Comment by dereuromark** [comment]
:+1: I am still on 3.1, but 3.2 should work as well.

**Comment by dereuromark** [comment]
I think this is still a very good feature if someone has time here.

**Comment by half2me** [comment]
Well I am using this in my `bootstrap.php` file and it seems to be working perfectly.
```php
/**
 * Queue
 */
Plugin::load('Queue');
Configure::write('Queue', [
    'workermaxruntime' => 0, // Start once
    'sleeptime' => 15,
]);
```

**Comment by dereuromark** [comment]
I would have thought the same :)
