### ISSUE TITLE
2.x QueueEmail fails if passing CakeEmail instead of array

### ISSUE THREAD

**Issue by challgren** [dereuromark/cakephp-queue#68]
Data is

`a:1:{s:8:"settings";O:9:"CakeEmail":36:{s:6:" * _to";a:1:{s:19:"challgren@gmail.com";s:19:"challgren@gmail.com";}s:8:" * _from";a:1:{s:18:"admin@teamcash.net";s:8:"TeamCash";}s:10:" * _sender";a:0:{}s:11:" * _replyTo";a:0:{}s:15:" * _readReceipt";a:0:{}s:14:" * _returnPath";a:0:{}s:6:" * _cc";a:0:{}s:7:" * _bcc";a:0:{}s:13:" * _messageId";b:1;s:10:" * _domain";s:15:"DESKTOP-RBHJA57";s:11:" * _subject";s:5:"About";s:11:" * _headers";a:0:{}s:10:" * _layout";s:7:"default";s:12:" * _template";s:0:"";s:14:" * _viewRender";s:4:"View";s:12:" * _viewVars";a:0:{}s:9:" * _theme";N;s:11:" * _helpers";a:1:{i:0;s:4:"Html";}s:15:" * _textMessage";s:0:"";s:15:" * _htmlMessage";s:0:"";s:11:" * _message";a:0:{}s:24:" * _emailFormatAvailable";a:3:{i:0;s:4:"text";i:1;s:4:"html";i:2;s:4:"both";}s:15:" * _emailFormat";s:4:"text";s:17:" * _transportName";s:18:"Mailchimp.Mandrill";s:18:" * _transportClass";O:17:"MandrillTransport":4:{s:9:" * _Email";N;s:10:" * _Socket";N;s:11:" * _headers";N;s:10:" * _config";a:2:{s:3:"key";s:22:"validkey";s:11:"useTemplate";b:1;}}s:7:"charset";s:5:"UTF-8";s:13:"headerCharset";s:5:"UTF-8";s:14:" * _appCharset";s:5:"UTF-8";s:15:" * _attachments";a:0:{}s:12:" * _boundary";N;s:10:" * _config";a:3:{s:9:"transport";s:18:"Mailchimp.Mandrill";s:3:"key";s:22:"validkey";s:11:"useTemplate";b:1;}s:15:" * _charset8bit";a:2:{i:0;s:5:"UTF-8";i:1;s:9:"SHIFT_JIS";}s:22:" * _contentTypeCharset";a:1:{s:14:"ISO-2022-JP-MS";s:11:"ISO-2022-JP";}s:16:" * _emailPattern";s:59:"/^((?:[\p{L}0-9.!#$%&'*+\/=?^_{|}~-]+)*@[\p{L}0-9-.]+)$/ui";s:15:" * _configClass";s:11:"EmailConfig";s:18:" * _configInstance";O:11:"EmailConfig":1:{s:7:"default";a:3:{s:9:"transport";s:18:"Mailchimp.Mandrill";s:3:"key";s:22:"validkey";s:11:"useTemplate";b:1;}}}}`

Error outputed is

> [2016-02-01 16:41:08] Looking for Job ...
> Running Job of type "Email"
> Warning Error: array_merge(): Argument #2 is not an array in [C:\Users\chall\teamcash-website\public_html\Plugin\Queue\Console\Command\Task\QueueEmailTask.php, line 99]
> 
> Warning Error: Invalid argument supplied for foreach() in [C:\Users\chall\teamcash-website\public_html\Plugin\Queue\Console\Command\Task\QueueEmailTask.php, line 100]
> 
> 2016-02-01 16:41:08 Error: You need to specify at least one destination for to, cc or bcc. (line 1164 in C:\Users\chall\teamcash-website\Vendor\cakephp\cakephp\lib\Cake\Network\Email\CakeEmail.php)
> # 0 C:\Users\chall\teamcash-website\public_html\Plugin\Tools\Lib\EmailLib.php(531): CakeEmail->send(NULL)
> # 1 C:\Users\chall\teamcash-website\public_html\Plugin\Queue\Console\Command\Task\QueueEmailTask.php(110): EmailLib->send(NULL)
> # 2 C:\Users\chall\teamcash-website\public_html\Plugin\Queue\Console\Command\QueueShell.php(216): QueueEmailTask->run(Array, '17')
> # 3 C:\Users\chall\teamcash-website\Vendor\cakephp\cakephp\lib\Cake\Console\Shell.php(451): QueueShell->runworker()
> # 4 C:\Users\chall\teamcash-website\Vendor\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(212): Shell->runCommand('runworker', Array)
> # 5 C:\Users\chall\teamcash-website\Vendor\cakephp\cakephp\lib\Cake\Console\ShellDispatcher.php(66): ShellDispatcher->dispatch()
> # 6 C:\Users\chall\teamcash-website\public_html\Console\cake.php(48): ShellDispatcher::run(Array)
> # 7 {main}
> 
> Job did not finish, requeued.

I would expect the job to complete successfully since I already provided a complete CakeEmail object to the createJob('email', $CakeEmail);

**Comment by dereuromark** [comment]
You are not supposed to pass an Object. Did you take a look at the test cases?

**Comment by challgren** [comment]
I couldn't find a test case for this instance as the code in Command\Task\QueueEmailTask doesn't have any code coverage. If I look at line 68 `if (is_object($email = $data['settings']) && $email instanceof CakeEmail) {` it appears when calling $queue->createJob('Email', array('settings'= > CakeEmail)) its expecting the settings var to be an instance of CakeEmail

**Comment by dereuromark** [comment]
You are right, CakeEmail should work.

**Comment by dereuromark** [comment]
OK, now I know what the issue was: It expected Tools\Mailer\Email instead.
I fix this and publish a new release this weekend.

**Comment by dereuromark** [comment]
SHould be all good now.

**Comment by houseoftech** [comment]
@dereuromark Was this fixed for the 2.x branch or only 3.x?

**Comment by dereuromark** [comment]
I am sry, not for 2.x. I will reopen then.

**Comment by challgren** [comment]
@houseoftech thank you

**Comment by dereuromark** [comment]
I commited the missing use statement. Please check.

**Comment by houseoftech** [comment]
I tested this a bit. It simply logs a blank email with no message body using the Debug transport. But if I remove all the code inside the `try {}` and just use `$result = $email->send();` everything works as expected.

When using the Debug transport I set the following:

    $config['log'] = true;
    $config['logTrace'] = 'debug';
    $config['transport'] = 'Debug';

**Comment by dereuromark** [comment]
Ok so the inital Problem is solved.
