### ISSUE TITLE
Queue performance on CakePHP 2.x

### ISSUE THREAD

**Issue by drmonkeyninja** [dereuromark/cakephp-queue#69]
We've been successfully using the Queue plugin on CakePHP 2.x sites for a while now, but on one site having issues with it running very slowly. The queue contains a large number of tasks for generating statistics and sending out emails in the background.

We've currently got it setup to run every 5 minutes via cron with the following configuration:-

```php
$config['Queue'] = array(
	// seconds to sleep() when no executable job is found
	'sleeptime' => 10,

	// probability in percent of a old job cleanup happening
	'gcprob' => 10,

	// time (in seconds) after which a job is requeued if the worker doesn't report back
	'defaultworkertimeout' => 120,

	// number of retries if a job fails or times out.
	'defaultworkerretries' => 4,

	// seconds of running time after which the worker will terminate (0 = unlimited)
	'workermaxruntime' => 300,

	// minimum time (in seconds) which a task remains in the database before being cleaned up.
	'cleanuptimeout' => 2592000,

	// instruct a Workerprocess quit when there are no more tasks for it to execute (true = exit, false = keep running)
	'exitwhennothingtodo' => true,

	// pid file path directory (by default goes to the app/tmp/queue folder)
	'pidfilepath' => TMP . 'queue' . DS,

	// determine whether logging is enabled
	'log' => true,

	// set to false to disable (tmp = file in TMP dir)
	'notify' => 'tmp'
);
```

Is there any way we could improve the queue's performance? Are we maybe missing something in our config? Even basic tasks that just perform a couple of simple queries appear to run slow at the moment.

We're looking at rewriting a number of our tasks to try and optimise them, but we would have expected to see the queue running faster than it currently does regardless.

Any suggestions would be greatly appreciated.

**Comment by dereuromark** [comment]
So how many records are in the DB table tops?
Any SQL debugging that show the queries?
Because that seems like the only bottleneck, the rest is just basic threaded PHP jobs.

**Comment by drmonkeyninja** [comment]
Unfortunately the queue has not been run until today despite tasks being queued up for some time so there is a lot of backlog. Today alone we have over 40K tasks. I suspect you're right about the queries being what is causing it to be slow and we are already looking into this. Just wanted to check if there were any other configuration options available to us.

Happy for this to be closed as it seems like the issue is our database/tasks.

**Comment by dereuromark** [comment]
You should send alerts/reports to the dev team if the queue piles up >> 1000 records IMO.

**Comment by drmonkeyninja** [comment]
Unfortunately this particular project has been one big nightmare. Basically it needed rushing out the door in a very incomplete and poorly tested state after the client learnt that the plug was being pulled on their existing site long before they were expecting. As their website was the whole point of their business there was no choice but to put live something I personally would never have approved (it is a long, complicated story). We were in an impossible situation. 

As a consequence we were asked not to run the queue which has lead to a build up of tasks that we must now process. Once existing tasks have been cleared it should run fine, but in its current state there's a lot to run.

After some tests we've found that our tasks themselves run *very* fast, but what is slowing everything down is the query the plugin performs to select the next task. This line in particular performs very badly:-

```php
$this->virtualFields['age'] = 'IFNULL(TIMESTAMPDIFF(SECOND, NOW(),notbefore), 0)';
```

Our plan is to run some code that will attempt to clear the queue quickly so that we can start running the queue plugin from a clean slate. 

Otherwise we are really happy with Queue and have used it on numerous projects very successfully. This is a very unusual situation we find ourselves in, and a somewhat temporary one.

**Comment by dereuromark** [comment]
Thanks for the feedback. It is good to hear that it actually performs under these high usage situations. Usually people tend to use it only for small mini projects :)
