### ISSUE TITLE
Prep 3.1.0 release

### ISSUE THREAD

**Issue by dereuromark** [dereuromark/cakephp-queue#71]
We need the tests to work again for this.

I could need a helping hand as the tests still fail for the "rate limit", seems like the 3.x upgrade wasnt fully BC yet.

**Comment by AlexMax** [comment]
I'm actually running into a couple of failing tests.  I spent some time today and managed to get a handle on `testCreateAndFetch` - it appears that it fails for me on line **147**.

As far as I can tell, the reason that test fails is that there are no `rate` parameters in the `$capabilities` array, and thus the conditional on line 220 of `QueuedTasksTable.php` fails.  Considering that the `2.x` branch has no `rate` parameter either, I don't know how the asserts starting on line 147 of the test method and on were ever supposed to pass in the first place, frankly.  I admit that I might have missed something, though.

**Comment by dereuromark** [comment]
The 2.x ones definitely passed so far, always.
So not sure what part of upgrading killed the tests to sometimes work and sometimes not.
Maybe some order clause or other random cause of failure.
