### ISSUE TITLE
Failing unit tests with Sqlite driver

### ISSUE THREAD

**Issue by AlexMax** [dereuromark/cakephp-queue#72]
I notice that if you try and run unit tests without any database parameters in the environment, the tests default to the Sqlite driver.

Looking over the codebase, it looks like there are many different instances of MySQL-isms in the code.  It would be nice if this plugin was database-agnostic.

**Comment by dereuromark** [comment]
Yes, that would be nice.
The tests currently also dont like the 3.x upgrade in general.
some weird failing test.
If you have time, it would be awesome if you could help out.

**Comment by half2me** [comment]
Hey, any progress on this? If there is a need I might be able to help make this database-agnostic.

**Comment by dereuromark** [comment]
Would be awesome

**Comment by dereuromark** [comment]
I think PostGres (see other ticket) has priority - but if SQLite can also work, even better!
Anyone willing to fix those 2-3 queries?

**Comment by dereuromark** [comment]
Refs https://github.com/dereuromark/cakephp-queue/compare/master...justinyost:master

**Comment by inoas** [comment]
:+1:

**Comment by dereuromark** [comment]
Tests passing, closing then.
