### ISSUE TITLE
Task timeout property not implemented (2.x)

### ISSUE THREAD

**Issue by wvdongen** [dereuromark/cakephp-queue#75]
It seems the timeout property of a Task does nothing in QueueShell.

See code starting at https://github.com/dereuromark/cakephp-queue/blob/2.x/Console/Command/QueueShell.php#L216

**Comment by dereuromark** [comment]
That might be true. The main timeout stuff is from outside (PHP lifetime set by the cronjob and global configs etc).
We should either remove or completel add it then.
Are you able to make a PR?
