### ISSUE TITLE
Unserialize giving offset error

### ISSUE THREAD

**Issue by half2me** [dereuromark/cakephp-queue#76]
I am always getting this error when running the worker

``` php
Notice Error: unserialize(): Error at offset 193 of 65535 bytes in [/var/www/clients/client1/web7/web/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php, line 212]

2016-03-15 15:13:43 Notice: Notice (8): unserialize(): Error at offset 193 of 65535 bytes in [/var/www/clients/client1/web7/web/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php, line 212]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 146
unserialize - [internal], line ??
Queue\Shell\QueueShell::runworker() - ROOT/vendor/dereuromark/cakephp-queue/src/Shell/QueueShell.php, line 212
Cake\Console\Shell::runCommand() - CORE/src/Console/Shell.php, line 444
Cake\Console\ShellDispatcher::_dispatch() - CORE/src/Console/ShellDispatcher.php, line 217
Cake\Console\ShellDispatcher::dispatch() - CORE/src/Console/ShellDispatcher.php, line 181
Cake\Console\ShellDispatcher::run() - CORE/src/Console/ShellDispatcher.php, line 127
[main] - ROOT/bin/cake.php, line 33
```

How about using BLOB type instead of TEXT in the database, to fix character encoding bugs.

**Comment by dereuromark** [comment]
Can you make a PR please?

**Comment by half2me** [comment]
Yeah, so the problem was not with char encoding, but with the max length for TEXT type. It was cutting off the end of the serialized object causing the errors.

Switch field type to LONGTEXT and everything should work fine

**Comment by dereuromark** [comment]
A PR with a migration file changing this would be very welcome.

**Comment by half2me** [comment]
I've looked into this, but I've only found Mysql or PostgreSql specific ways of solving this. Phinx which cakePHP's migrations uses has a constraint for how long the text can be, but from what I've found, you need to choose mysql or postgresql. :( So I don't have a perfect solution yet.

**Comment by half2me** [comment]
@dereuromark is there some way to detect what database is being used? Postgres and MySQL have support for longer TEXT fields. I don't know about sqlite or MSSQL...

**Comment by half2me** [comment]
https://github.com/cakephp/migrations/issues/211

**Comment by half2me** [comment]
So here is my PR. I also wrote up an issue for baking a snapshot of the db not writing the limit field properly to cakephp/migrations

**Comment by dereuromark** [comment]
Cool, thx!
Does this already work or shall we wait until the Migrations PR is merged?

**Comment by half2me** [comment]
This already works! The migrations PR just removes the need to do this all manually, and takes care of this when you are first creating the snapshot.

**Comment by half2me** [comment]
When will this be in a release?
