### ISSUE TITLE
[Question] Nested Tasks

### ISSUE THREAD

**Issue by flashios09** [dereuromark/cakephp-queue#83]
Hi @dereuromark ,
Is it possible to call a task inside another task file ?
eg.:
A task generate a pdf file(QueuePdfTask.php), inside the run method after generating the pdf file send an email using another task(QueueEmailTask.pdf) 

Thanks

**Comment by dereuromark** [comment]
Sure why not

**Comment by flashios09** [comment]
I created a Pdf task(inspired from the Email task), the CronJob works
```
---------------------------------------------------------------
[2016-03-26 11:36:23] Looking for Job ...
Running Job of type "Pdf"
---------------------------------------------------------------
CakePHP Queue Pdf task.
---------------------------------------------------------------
 ->Success, the Pdf Job was run.<-
 
 
Job Finished.
```
The database `queued_tasks` table is updated also
http://cl.ly/280t1U2v1h1j

debug the ```$QueuedTasks->createJob('Pdf', compact('communication') + $options);``` will return a QueuedTasks Entity.

But **the pdf wasn't generated** !
If i copy/paste the code inside the `QueuePdfTask.php::run($data, $id = null)` to a controller action and test it, **it works and the pdf file will be generated**.

That's a gist of the QueuePdfTask.php
 https://gist.github.com/flashios09/405063d1ed7711620cfe

Have i missed something ? How can i debug a var inside the run method ? Is there a chmod that i have to force to the **App\Shell\Task\QueuePdfTask.php** ?
