### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by mconnorsmccann** [dereuromark/cakephp-queue#86]
Is it possible to check if a task already exists before adding it again so its not fired off twice?

**Comment by dereuromark** [comment]
Why would you try to add it twice to begin with?

**Comment by mconnorsmccann** [comment]
I wouldn't, but I was wondering if it was possible I could double check that a task wasn't already queued.

**Comment by dereuromark** [comment]
If you Pass a unique identifier it might be able to do a lookup om that manually.

**Comment by mconnorsmccann** [comment]
Thank you very much, I will look into that. I really appreciate the plugin, its working out really well for us, thanks again
