### ISSUE TITLE
20161319000000_increase_data_size.php fails on Postgres

### ISSUE THREAD

**Issue by justinatack** [dereuromark/cakephp-queue#92]
When running this Queue migration on Postgres I get the following error.

```
[PDOException]                                                               
  SQLSTATE[42601]: Syntax error: 7 ERROR:  type modifier is not allowed for t  
  ype "text" 
```

If I comment out the following then the migration run fine.

```
$table->changeColumn('data', 'text', [
            // 'length' => 4294967295,
            'null' => true,
            // 'default' => null,
        ]);
```

Is this column change needed?

**Comment by dereuromark** [comment]
This was a very recent change. See https://github.com/dereuromark/cakephp-queue/pull/80 .

**Comment by dereuromark** [comment]
Any follow up here?
Also refs Postgres support https://github.com/dereuromark/cakephp-queue/issues/106

**Comment by dereuromark** [comment]
The try catch fixes this, right?
