### ISSUE TITLE
update in jobRequest on mysql cluster throws error

### ISSUE THREAD

**Issue by Graziel** [dereuromark/cakephp-queue#95]
looks like this specific combination of 'update', 'text' field type, 'order by' datetime & mysql cluster throws error:

```
[PDOException] SQLSTATE[HY000]: General error: 1296 Got error 4265 'The method is not valid in current blob state' from NDBCLUSTER
```

while it looks like it can be mysql cluster bug (works ok with InnoDB engine) is the order by even necessary? its already ordered in first query

**Comment by Graziel** [comment]
verified bug in mysql cluster
https://bugs.mysql.com/bug.php?id=81874

**Comment by dereuromark** [comment]
Maybe we can remove the order here then.
Feel free to make a PR, lets see if the tests pass etc.

**Comment by Graziel** [comment]
bump for glory
