### ISSUE TITLE
shell issuse in cakephp2.4

### ISSUE THREAD

**Issue by deepika1308** [dereuromark/cakephp-queue#98]
Hello, 
sir i have problem in shell loading in cakephp 2.4 but does understand how to solve this. When i type "Console/cake Queue.Queue " in cake console and my home directory is 
cake>app>Console/cake Queue.Queue 
Error: Shell class QueueShell could not be found.
#0 /var/www/html/cake1/lib/Cake/Console/ShellDispatcher.php(203): ShellDispatcher->_getShell('Queue.Queue')
#1 /var/www/html/cake1/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#2 /var/www/html/cake1/app/Console/cake.php(47): ShellDispatcher::run(Array)
#3 {main}
Please Help Me..

**Comment by dereuromark** [comment]
Please make sure the plugin is loaded as documented in your bootstrap.
