### ISSUE TITLE
Getting emails twice from Queue

### ISSUE THREAD

**Issue by hussainarifsufalam** [dereuromark/cakephp-queue#99]
Hello Mark,
First of all big thank to you for developing such a nice plugin.
I have used this plugin in my web application which is developed under cakephp 2.x version. Issue I am facing when I am adding a send Email task into Queue, it will send email twice to each recipients. 
After debugging this issue I found that there are neither duplicate entries into the queued_task table nor repeated users data to send email. 
Can you please provide a solution for this ?

**Comment by dereuromark** [comment]
This must be a mistake on your end.
Maybe you are adding a recipient twice in "to" or alike? Check the email headers as well.

**Comment by hussainarifsufalam** [comment]
Thanks for the prompt reply. As I have mentioned above, recipients are not added twice. I have make logs to debug it also.

**Comment by dereuromark** [comment]
How many workers are you running? Is it possible two pick it up at the same time or sth?
Never heard of it so far, and people are sending millions of mails this way so far.

**Comment by hussainarifsufalam** [comment]
I am running with single worker only. Following are my settings
Current Settings:
* sleeptime: 15
* gcprob: 10
* defaultworkertimeout: 120
* defaultworkerretries: 4
* workermaxruntime: 0
* cleanuptimeout: 10
* exitwhennothingtodo:
* pidfilepath: /path/to/tmp/directory/
* log:
* notify: tmp

**Comment by hussainarifsufalam** [comment]
as such is there any other way using which i can kill all the erokers on a centos system. I know it is work in progress.

Thanks.

**Comment by dereuromark** [comment]
Check "top" and the processes running.

**Comment by hussainarifsufalam** [comment]
I checked that also and kill every runworker process and restarted again with Cron job, but issue is not resolved yet.

**Comment by dereuromark** [comment]
@ all: Anyone else having this issue?

**Comment by dhinesh03** [comment]
I too have this issue but i've been running 2 workers always. i've checked the code QueuedTasksTable->requestJob , second worker fetch the job before save ('workerkey' => $key and 'fetched' => $now )   action of first worker.

**Comment by dereuromark** [comment]
Can we put transactionals around it here to prevent this from happenning?
Will only work for InnoDB then, right?

**Comment by Spriz** [comment]
We're debugging that queue jobs might be running multiple times as well, any findings on your end(s) ?

**Comment by dereuromark** [comment]
Would be useful to know when this regression happened, or how to reproduce. So far my tests didnt't reveal much.

**Comment by Spriz** [comment]
I'll try to dig deeper into cakephp-queue.. until now I assumed it was in our code somewhere.

**Comment by Spriz** [comment]
Could it be the issue comes up with a lot of entries in the queued_tasks table? Eg if the `SELECT` statement runs for 1500-2000ms? Then multiple workers would run the same task?

**Comment by dereuromark** [comment]
Most certainly that could be the issue, should be easy to test with a unit test and sleep() right?
We should make sure there is a transaction around the select + update part so it cannot happen that those are fetched two times independently.

**Comment by johnmullin2003** [comment]
Hi dereuromark,

Same issue here.
Duplicate entries into the queued_task table.
I used the queue cfg as explained in tutorial.

Ubuntu 16.04
PHP 7
MySQL 5.7.12

**Comment by dereuromark** [comment]
why do you want to kill one? they should be short-timed and timeout themselves in a clean way.

**Comment by dereuromark** [comment]
Are we talking about 2.x or 3.x?

**Comment by dereuromark** [comment]
Please also check develop branch if the recent fixes resolve this issue.

**Comment by johnmullin2003** [comment]
Thanks @dereuromark .
I'm using the 3.x release.

It seems my issue was releated to the fact the tasks were not properly killed.
I used you suggestion and I set them with timeout.
Everything seems OK now.

Thanks again

**Comment by doonot** [comment]
Updating from 3.16 to 4.4.0 fixed this problem for us.

**Comment by dereuromark** [comment]
Any idea what it was?
